.TH XORG-X11-FONTS-UPDATE-DIRS 1 "25 July 2014"
.SH NAME
xorg-x11-fonts-update-dirs \- update X11 font directories
.SH SYNOPSIS
.B xorg-x11-fonts-update-dirs [--skip-fontscale] [--need-ttmkfdir] path
.SH DESCRIPTION
.PP
The 
.B xorg-x11-fonts-*
rpm packages call
.I xorg-x11-fonts-update-dirs
during %post and %postun to update the X11 font indices.
This script may change in incompatible ways without notice and 
you should not run this script manually or rely on it otherwise.
To manually update the font indices invoke 
.B mkfontscale
and 
.B ttmkfdir 
directly as required.
.PP
.SH "SEE ALSO"
mkfontscale(1)
ttmkfdir(1)
