# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG BASE_IMAGE

FROM $BASE_IMAGE

@INCLUDE_MAIN_RUN_INSTRUCTION@

RUN tdnf update -y && \
   tdnf install -y azurelinux-repos-cloud-native && \
   tdnf update -y && \
   tdnf install -y qemu-img rpm coreutils util-linux systemd openssl \
      sed createrepo_c squashfs-tools cdrkit parted e2fsprogs dosfstools \
      xfsprogs zstd veritysetup grub2 grub2-pc systemd-ukify binutils lsof \
      python3 python3-pip jq oras && \
   tdnf clean all

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
