id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches: []
    eventResponderTasks:
      - if:
          - payloadType: Pull_Request
        then:
          - if:
              - filesMatchPattern:
                  pattern: "^(SPECS|SPECS-EXTENDED|SPECS-SIGNED)/"
                  matchAny: true
            then:
              - addLabel:
                  label: Packaging
          - if:
              - filesMatchPattern:
                  pattern: "^SPECS-EXTENDED/"
                  matchAny: true
            then:
              - addLabel:
                  label: specs-extended
          - if:
              - filesMatchPattern:
                  pattern: "^toolkit/docs/"
                  matchAny: true
            then:
              - addLabel:
                  label: documentation
          - if:
              - filesMatchPattern:
                  pattern: "^toolkit/(tools|scripts)/"
                  matchAny: true
            then:
              - addLabel:
                  label: Tools
          - if:
              - filesMatchPattern:
                  pattern: "^toolkit/(imageconfigs|tools/imagegen/configuration)/"
                  matchAny: true
            then:
              - addLabel:
                  label: Schema
        description:
      - if:
          - payloadType: Pull_Request
          - filesMatchPattern:
              pattern: (CVE|cve)-\d+-\d+\.(no)?patch
        then:
          - addLabel:
              label: security
        description:
      - if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - isActivitySender:
              user: CBL-Mariner-Bot
              issueAuthor: False
        then:
          - addLabel:
              label: Automatic PR
        description:
      - if:
          - payloadType: Pull_Request
        then:
          - if:
              - targetsBranch:
                  branch: main
            then:
              - addLabel:
                  label: main
          - if:
              - targetsBranch:
                  branch: 2.0
            then:
              - addLabel:
                  label: 2.0
          - if:
              - targetsBranch:
                  branch: 3.0-dev
            then:
              - addLabel:
                  label: 3.0-dev
          - if:
              - targetsBranch:
                  branch: 3.0
            then:
              - addLabel:
                  label: 3.0
          - if:
              - targetsBranch:
                  branch: fasttrack/2.0
            then:
              - addLabel:
                  label: fasttrack/2.0
          - if:
              - targetsBranch:
                  branch: fasttrack/3.0
            then:
              - addLabel:
                  label: fasttrack/3.0
        description:
onFailure:
onSuccess:
