#!/bin/sh 

COMPSFILE=$1

if [ -z "$COMPSFILE" ]; then
    echo "Usage: $0 <compsfile>"
    exit 1
fi

LANG=C intltool-merge -x -u po/ $COMPSFILE.in $COMPSFILE
case $COMPSFILE in
  comps-eln.xml) xsltproc --stringparam distro eln --novalid -o $COMPSFILE comps-distro-only.xsl $COMPSFILE ;;
esac
