#! /bin/bash
# Copyright (C) 2005 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.


FRESHCLAM_MOD=$[ 3*60 ]		# 3 hours

f=/etc/sysconfig/freshclam
test ! -e "$f" || . "$f"


case x"$1" in
    (xnow)		FRESHCLAM_DELAY=0;;
    (x|xrandom)		: ${FRESHCLAM_DELAY:=$[ 0x`hostid` ]};;
    (*)			FRESHCLAM_DELAY=$1;;
esac

set -e

case $FRESHCLAM_DELAY in
    (disabled-warn)
	echo $"\
WARNING: update of clamav database is disabled; please see
  '$f'
  for information how to enable the periodic update resp. how to turn
  off this message." >&2
	exit 1
	;;

    (disabled)
	exit 0
	;;

    (*)
	let FRESHCLAM_MOD*=60
	sleep $[ (FRESHCLAM_DELAY % FRESHCLAM_MOD + FRESHCLAM_MOD) % FRESHCLAM_MOD ]
	;;
esac

/usr/bin/freshclam --quiet > /dev/null
