# Java portable package has a bootstrap stage which requires N-1 or N version of
# JDK. For stage-1 we have an _option_ to pull deps from elsewhere. For stage-2
# packages are restricted to what we build. We do not build jdk 24 and only 'N' or
# 25 will work for us.
#
# The second workaround is to deliver the appropriate minor version of java portable.
# Java 25 sdk needs 25.0.0.0.32 version of the -sources as a build requires. We pull
# from the last snapshot of the spec at that version. 

[components.java-25-openjdk-portable]
spec = { type = "upstream", upstream-distro = { name = "fedora", version = "43", snapshot = "2025-07-22T00:00:00-08:00" } }

[[components.java-25-openjdk-portable.overlays]]
description = "Override buildjdkver to use Java 25 instead of 24 for bootstrap"
type = "spec-search-replace"
regex = '^%global buildjdkver 24$'
replacement = '%global buildjdkver 25'

# We are working off an older version of the -portable spec which hardcoded BuildRequires
# to java-latest*. The buildjdkver change above will not remove that dependency. We have
# to explicitly replace the -latest dependency with -25.
[[components.java-25-openjdk-portable.overlays]]
description = "Remove upstream java-latest BuildRequires to avoid pulling java-latest-openjdk-devel"
type = "spec-remove-tag"
tag = "BuildRequires"
value = "java-latest-openjdk-devel"

[[components.java-25-openjdk-portable.overlays]]
description = "Add BuildRequires on java-25-openjdk-devel instead of java-latest-openjdk-devel"
type = "spec-add-tag"
tag = "BuildRequires"
value = "java-25-openjdk-devel"
