[components.SymCrypt-OpenSSL]
spec = { type = "local", path = "SymCrypt-OpenSSL.spec" }

[[components.SymCrypt-OpenSSL.source-files]]
filename = "SymCrypt-OpenSSL-1.11.0.tar.gz"
hash = "a4c751d5fab8ff069b17b2f4cd1eb8acdbbaf7738d9917cfe453420e064b3e31"
hash-type = "SHA256"
origin = { type = "download", uri = "https://github.com/microsoft/SymCrypt-OpenSSL/archive/v1.11.0.tar.gz" }
