[components.gyp]
# Upstream Release: 0.60%{?revision:.%{revision}git}%{?dist}
release = { calculation = "static", counter = { source = "release-tag", regex = '^0\.([0-9]+)%\{\?revision:\.%\{revision\}git\}(?:%\{\??dist\})?$' } }
