.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ACPIBIN 1 "January 23, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
acpibin \- ACPI binary AML file utility
.SH SYNOPSIS
.B acpibin
.RI [ <option> ... ]

.SH DESCRIPTION
This manual page briefly documents the
.B acpibin
command. The option list is taken from the acpibin interactive help.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.B acpibin
is a command provided to perform some basic and common operations on
AML binary files.
.PP
Much more detailed documentation may be found at
http://www.acpica.org/documentation/.

.SH OPTIONS

.PP
.TP
.B \-c <file1> <file2>
Compare two binary AML files
.TP
.B \-d <in> <out>
Dump AML binary to text file
.TP
.B \-e <sig> <in> <out>
Extract binary AML table from acpidump file
.TP
.B \-h <file>
Display table header for binary AML file
.TP
.B \-s <file>
Update checksum for binary AML file
.TP
.B \-t
Terse mode

.SH AUTHOR
acpibin was written by Robert Moore <robert.moore@intel.com>.
.PP
This manual page was written by Al Stone <ahs3@redhat.com> for the
Fedora project (but may be used by others).
