FROM mcr.microsoft.com/cbl-mariner/base/core:2.0

# RUN tdnf update -y && tdnf install -y mariner-repos-extended
# no dd -> coreutils
# no lsblk losetup sfdisk flock blkid -> util-linux
# no udevadm -> systemd
RUN tdnf update -y && tdnf install -y sudo qemu-img rpm coreutils util-linux systemd openssl sed squashfs-tools dosfstools genisoimage

RUN mkdir /input && mkdir /output
COPY . /mic

ENTRYPOINT ["/mic/generate-iso.sh"]
