#! /bin/sh

if test $# != 1; then
  echo usage: update-gtk-immodules host_triplet 1>&2
  exit 1
fi
 
umask 022

case "$1" in
  alpha*|ia64*|ppc64*|powerpc64*|s390x*|x86_64*|aarch64*)
   /usr/bin/gtk-query-immodules-2.0-64 --update-cache
   ;;
  *)
   /usr/bin/gtk-query-immodules-2.0-32 --update-cache
   ;;
esac
