parameters:
- name: publishingLevel
  type: string
- name: architecture
  type: string
- name: containerImages
  type: object
- name: agentPool
  type: object
- name: selfRepoName
  type: string
- name: selfRepoRoot
  type: string

stages:
- template: BuildContainersValidation.yml@${{ parameters.selfRepoName }}
  parameters:
    stageName: validation_stage
    publishingLevel: ${{ parameters.publishingLevel }}
    agentPool: ${{ parameters.agentPool }}

- template: BuildContainers.yml@${{ parameters.selfRepoName }}
  parameters:
    dependsOnStage: validation_stage
    stageName: build_containers_stage
    publishingLevel: ${{ parameters.publishingLevel }}
    architecture: ${{ parameters.architecture }}
    containerImages: ${{ parameters.containerImages }}
    agentPool: ${{ parameters.agentPool }}
    selfRepoName: ${{ parameters.selfRepoName }}
    selfRepoRoot: ${{ parameters.selfRepoRoot }}

- template: BuildContainersWrapup.yml@${{ parameters.selfRepoName }}
  parameters:
    dependsOnStage: build_containers_stage
    containerImages: ${{ parameters.containerImages }}
    agentPool: ${{ parameters.agentPool }}
