#!/bin/sh

# This file was created with portions of the original SysV init script shipped 
# with hsqldb

# Copyright (c) 2001-2004, The HSQL Development Group
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# Redistributions of source code must retain the above copyright notice, this
# list of conditions and the following disclaimer.
#
# Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# Neither the name of the HSQL Development Group nor the names of its
# contributors may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL HSQL DEVELOPMENT GROUP, HSQLDB.ORG,
# OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


# $MAX_START_SECS from when the Server/WebServer is started.
MAX_START_SECS=60

# Class in the org.hsqldb package to start.
# At this time, only the values "Server" or "WebServer" will work.
TARGET_CLASS=Server

. /etc/hsqldb.conf

. /usr/share/java-utils/java-functions

[ -z "$JAVA_EXECUTABLE" ] && {
    set_javacmd
    JAVA_EXECUTABLE=${JAVACMD}
}

# PROPERTY_FILE is a derived value.
case "$TARGET_CLASS" in
    Server) PROPERTY_FILE="$SERVER_HOME"/server.properties;;
    WebServer) PROPERTY_FILE="$SERVER_HOME"/webserver.properties;;
    *)
        echo 'Unsupported value for $TARGET_CLASS:  '"$TARGET_CLASS" 1>&2
        exit 2;;
esac
[ -f "$PROPERTY_FILE" ] || {
    echo "'$PROPERTY_FILE' is missing" 1>&2
    exit 2
}
[ -r "$PROPERTY_FILE" ] || {
    echo "'$PROPERTY_FILE' isn't readable" 1>&2
    exit 2
}

AUTH_FILE_SWITCH=
# N.b., there will be a problem if there are special characters or
# spaces inside of $AUTH_FILE.
[ -n "$AUTH_FILE" ] && AUTH_FILE_SWITCH="-Dsqltoolsprayer.rcfile=$AUTH_FILE"

# Might as well set CLASSPATH for a cleaner command.
CLASSPATH="$HSQLDB_JAR_PATH"
export CLASSPATH

sleep 1

"$JAVA_EXECUTABLE" $AUTH_FILE_SWITCH $CLIENT_JVMARGS \
    "-Dsqltoolsprayer.propfile=$PROPERTY_FILE" \
    "-Dsqltoolsprayer.maxtime=${MAX_START_SECS}000" \
    org.hsqldb.cmdline.SqlToolSprayer '' db0-url
