## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 2;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

# Generated by rust2rpm 27
# * tests can only be compiled in-tree
%bcond check 0
%global debug_package %{nil}

%global crate serde

Name:           rust-serde
Version:        1.0.228
Release:        %autorelease
Summary:        Generic serialization/deserialization framework

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/serde
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A generic serialization/deserialization framework.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%doc %{crate_instdir}/crates-io.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+alloc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+alloc-devel %{_description}

This package contains library source intended for building other packages which
use the "alloc" feature of the "%{crate}" crate.

%files       -n %{name}+alloc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+derive-devel %{_description}

This package contains library source intended for building other packages which
use the "derive" feature of the "%{crate}" crate.

%files       -n %{name}+derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rc-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rc-devel %{_description}

This package contains library source intended for building other packages which
use the "rc" feature of the "%{crate}" crate.

%files       -n %{name}+rc-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_derive-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_derive" feature of the "%{crate}" crate.

%files       -n %{name}+serde_derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
## START: Generated by rpmautospec
* Wed Apr 22 2026 azldev <azurelinux@microsoft.com> - 1.0.228-2
- Latest state for rust-serde

* Thu Oct 23 2025 Fabio Valentini <decathorpe@gmail.com> - 1.0.228-1
- Update to version 1.0.228; Fixes RHBZ#2397127

* Wed Sep 17 2025 Fabio Valentini <decathorpe@gmail.com> - 1.0.225-1
- Update to version 1.0.225; Fixes RHBZ#2395002

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.219-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Sat Apr 26 2025 Benjamin A. Beasley <code@musicinmybrain.net> - 1.0.219-1
- Update to version 1.0.219; Fixes RHBZ#2351000

* Tue Mar 04 2025 Fabio Valentini <decathorpe@gmail.com> - 1.0.218-1
- Update to version 1.0.218; Fixes RHBZ#2346757

* Sun Jan 19 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.217-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Sat Jan 04 2025 Fabio Valentini <decathorpe@gmail.com> - 1.0.217-1
- Update to version 1.0.217; Fixes RHBZ#2334633

* Mon Dec 16 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.216-1
- Update to version 1.0.216; Fixes RHBZ#2331632

* Wed Nov 13 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.215-1
- Update to version 1.0.215; Fixes RHBZ#2325334

* Tue Nov 05 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.214-1
- Update to version 1.0.214; Fixes RHBZ#2320872

* Wed Sep 18 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.210-1
- Update to version 1.0.210; Fixes RHBZ#2310491

* Mon Sep 02 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.209-1
- Update to version 1.0.209; Fixes RHBZ#2304002

* Fri Aug 09 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.205-1
- Update to version 1.0.205; Fixes RHBZ#2303613

* Sat Jul 20 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.204-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Sun Jul 07 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.204-1
- Update to version 1.0.204; Fixes RHBZ#2296130

* Tue May 28 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.203-1
- Update to version 1.0.203; Fixes RHBZ#2283248

* Tue May 07 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.200-1
- Update to version 1.0.200; Fixes RHBZ#2277462

* Tue Apr 23 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.198-1
- Update to version 1.0.198; Fixes RHBZ#2275364

* Fri Mar 08 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.197-1
- Update to version 1.0.197; Fixes RHBZ#2265025

* Tue Jan 30 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.196-1
- Update to version 1.0.196; Fixes RHBZ#2260590

* Sat Jan 27 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.195-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Fri Jan 12 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.195-1
- Update to version 1.0.195; Fixes RHBZ#2257011

* Wed Jan 03 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.194-1
- Update to version 1.0.194; Fixes RHBZ#2256427

* Thu Nov 30 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.193-1
- Update to version 1.0.193; Fixes RHBZ#2250758

* Fri Nov 10 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.192-1
- Update to version 1.0.192; Fixes RHBZ#2246257

* Tue Oct 17 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.189-1
- Update to version 1.0.189; Fixes RHBZ#2243779

* Fri Sep 15 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.188-1
- Update to version 1.0.188; Fixes RHBZ#2234333

* Wed Aug 23 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.185-1
- Update to version 1.0.185; Fixes RHBZ#2227376

* Thu Jul 27 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.177-2
- Rebuild for serde_derive fixes

* Thu Jul 27 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.177-1
- Update to version 1.0.177; Fixes RHBZ#2224131

* Fri Jul 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.171-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Fri Jul 14 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.171-1
- Update to version 1.0.171; Fixes RHBZ#2221001

* Wed Jul 05 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.166-1
- Update to version 1.0.166; Fixes RHBZ#2213417

* Mon May 22 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.163-1
- Update to version 1.0.163; Fixes RHBZ#2203022

* Mon May 08 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.162-1
- Update to version 1.0.162; Fixes RHBZ#2193275

* Mon Apr 17 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.160-1
- Update to version 1.0.160; Fixes RHBZ#2185731

* Thu Mar 30 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.159-1
- Update to version 1.0.159; Fixes RHBZ#2182292

* Wed Mar 22 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.158-1
- Update to version 1.0.158; Fixes RHBZ#2176636

* Tue Mar 07 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.153-1
- Update to version 1.0.153; Fixes RHBZ#2176251

* Fri Feb 03 2023 Fabio Valentini <decathorpe@gmail.com> - 1.0.152-1
- Update to version 1.0.152; Fixes RHBZ#2154419

* Sat Jan 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.150-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Tue Dec 13 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.150-1
- Update to version 1.0.150; Fixes RHBZ#2136788

* Sat Oct 08 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.145-1
- Update to version 1.0.145; Fixes RHBZ#2129166

* Mon Aug 22 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.144-1
- Update to version 1.0.144; Fixes RHBZ#2120031

* Fri Aug 12 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.143-1
- Update to version 1.0.143; Fixes RHBZ#2114947

* Tue Aug 02 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.141-1
- Update to version 1.0.141; Fixes RHBZ#2109228

* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.139-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Sun Jul 17 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.139-1
- Update to version 1.0.139; Fixes RHBZ#2105888

* Fri Jul 08 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.138-1
- Update to version 1.0.138; Fixes RHBZ#2103348

* Fri May 13 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.137-1
- Update to version 1.0.137; Fixes RHBZ#2080703

* Thu Feb 03 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.136-1
- Update to version 1.0.136; Fixes RHBZ#2043972

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.134-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Fri Jan 21 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.134-1
- Update to version 1.0.134; Fixes RHBZ#2043390

* Wed Jan 05 2022 Fabio Valentini <decathorpe@gmail.com> - 1.0.133-1
- Update to version 1.0.133; Fixes RHBZ#2036456

* Tue Dec 21 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.132-1
- Update to version 1.0.132; Fixes RHBZ#2033427

* Thu Dec 09 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.131-1
- Update to version 1.0.131; Fixes RHBZ#2030522

* Wed Sep 01 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.130-1
- Update to version 1.0.130; Fixes RHBZ#1996898

* Sun Aug 22 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.128-1
- Update to version 1.0.128; Fixes RHBZ#1996310

* Sun Aug 01 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.127-1
- Update to version 1.0.127; Fixes RHBZ#1988652

* Fri Jul 23 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.126-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Mon May 17 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.126-1
- Update to version 1.0.126.

* Wed Mar 24 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.125-1
- Update to version 1.0.125.

* Thu Mar 04 2021 Fabio Valentini <decathorpe@gmail.com> - 1.0.123-1
- Update to version 1.0.123.

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.119-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Tue Jan 12 09:29:28 CET 2021 Igor Raits <ignatenkobrain@fedoraproject.org> - 1.0.119-1
- Update to 1.0.119 (Fixes: RHBZ#1915056)

* Mon Dec 07 2020 Fabio Valentini <decathorpe@gmail.com> - 1.0.118-1
- Update to version 1.0.118.

* Tue Nov 10 2020 Fabio Valentini <decathorpe@gmail.com> - 1.0.117-1
- Update to version 1.0.117.

* Fri Sep 11 2020 Josh Stone <jistone@redhat.com> - 1.0.116-1
- Update to 1.0.116

* Thu Aug 20 2020 Josh Stone <jistone@redhat.com> - 1.0.115-1
- Update to 1.0.115

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.114-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Jul 10 2020 Josh Stone <jistone@redhat.com> - 1.0.114-1
- Update to 1.0.114

* Fri Jun 19 2020 Josh Stone <jistone@redhat.com> - 1.0.113-1
- Update to 1.0.113

* Sun May 31 10:22:53 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 1.0.111-1
- Update to 1.0.111

* Sun May 10 14:21:45 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 1.0.110-1
- Update to 1.0.110

* Fri May 08 2020 Josh Stone <jistone@redhat.com> - 1.0.107-1
- Update to 1.0.107

* Sat Apr 04 2020 Josh Stone <jistone@redhat.com> - 1.0.106-1
- Update to 1.0.106

* Wed Mar 18 2020 Josh Stone <jistone@redhat.com> - 1.0.105-1
- Update to 1.0.105

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.104-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Dec 16 2019 Josh Stone <jistone@redhat.com> - 1.0.104-1
- Update to 1.0.104

* Thu Nov 28 13:51:40 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.103-1
- Update to 1.0.103

* Tue Nov 19 09:40:05 CET 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.102-1
- Update to 1.0.102

* Sat Sep 21 09:00:38 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.101-1
- Update to 1.0.101

* Sun Sep 08 15:48:19 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.100-1
- Update to 1.0.100

* Mon Aug 26 05:31:03 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.99-1
- Update to 1.0.99

* Sun Jul 28 21:27:39 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.98-1
- Update to 1.0.98

* Sun Jul 28 18:22:23 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.97-1
- Update to 1.0.97

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.94-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Jun 30 12:01:36 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.94-1
- Update to 1.0.94

* Mon Jun 24 21:37:15 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.93-1
- Update to 1.0.93

* Thu Jun 20 11:58:08 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.92-3
- Regenerate

* Sun Jun 09 11:19:47 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.92-2
- Regenerate

* Fri May 31 2019 Josh Stone <jistone@redhat.com> - 1.0.92-1
- Update to 1.0.92

* Tue May 07 14:43:45 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.91-1
- Update to 1.0.91

* Wed Apr 03 2019 Josh Stone <jistone@redhat.com> - 1.0.90-1
- Update to 1.0.90

* Sun Mar 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.89-2
- Do not pull optional dependencies

* Fri Mar 01 2019 Josh Stone <jistone@redhat.com> - 1.0.89-1
- Update to 1.0.89

* Tue Feb 19 2019 Josh Stone <jistone@redhat.com> - 1.0.88-1
- Update to 1.0.88

* Sun Feb 10 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.87-1
- Update to 1.0.87

* Sun Feb 03 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.86-1
- Update to 1.0.86

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.85-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Sun Jan 20 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.85-1
- Update to 1.0.85

* Tue Jan 08 2019 Josh Stone <jistone@redhat.com> - 1.0.84-1
- Update to 1.0.84

* Wed Dec 12 2018 Josh Stone <jistone@redhat.com> - 1.0.82-1
- Update to 1.0.82

* Mon Dec 10 2018 Josh Stone <jistone@redhat.com> - 1.0.81-1
- Update to 1.0.81

* Fri Oct 26 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.80-2
- Adapt to new packaging

* Mon Oct 22 2018 Josh Stone <jistone@redhat.com> - 1.0.80-1
- Update to 1.0.80

* Sun Oct 07 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.79-2
- Run tests in infrastructure

* Mon Sep 17 2018 Josh Stone <jistone@redhat.com> - 1.0.79-1
- Update to 1.0.79

* Tue Sep 11 2018 Josh Stone <jistone@redhat.com> - 1.0.78-1
- Update to 1.0.78

* Fri Sep 07 2018 Josh Stone <jistone@redhat.com> - 1.0.77-1
- Update to 1.0.77

* Wed Aug 08 2018 Josh Stone <jistone@redhat.com> - 1.0.71-1
- Update to 1.0.71

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.70-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Wed Jul 11 2018 Josh Stone <jistone@redhat.com> - 1.0.70-1
- Update to 1.0.70

* Tue Jul 03 2018 Josh Stone <jistone@redhat.com> - 1.0.69-1
- Update to 1.0.69

* Fri Jun 29 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.68-1
- Update to 1.0.68

* Wed Jun 27 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.67-1
- Update to 1.0.67

* Tue Jun 05 2018 Josh Stone <jistone@redhat.com> - 1.0.66-1
- Update to 1.0.66

* Tue May 29 2018 Josh Stone <jistone@redhat.com> - 1.0.63-1
- Update to 1.0.63

* Mon May 28 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.62-1
- Update to 1.0.62

* Sat May 26 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.60-1
- Update to 1.0.60

* Tue May 22 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.59-1
- Update to 1.0.59

* Sun May 20 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.58-1
- Update to 1.0.58

* Sat May 19 2018 Josh Stone <jistone@redhat.com> - 1.0.56-1
- Update to 1.0.56

* Mon May 14 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.55-1
- Update to 1.0.55

* Sat May 12 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.54-1
- Update to 1.0.54

* Thu May 10 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.52-1
- Update to 1.0.52

* Wed May 09 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.51-1
- Update to 1.0.51

* Tue May 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.50-1
- Update to 1.0.50

* Mon May 07 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.47-1
- Update to 1.0.47

* Mon May 07 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.46-1
- Update to 1.0.46

* Wed May 02 2018 Josh Stone <jistone@redhat.com> - 1.0.45-1
- Update to 1.0.45

* Tue Apr 24 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.43-1
- Update to 1.0.43

* Sun Apr 22 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.42-1
- Update to 1.0.42

* Fri Apr 20 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.41-1
- Update to 1.0.41

* Tue Apr 17 2018 Josh Stone <jistone@redhat.com> - 1.0.39-1
- Update to 1.0.39

* Mon Apr 16 2018 Josh Stone <jistone@redhat.com> - 1.0.38-1
- Update to 1.0.38

* Tue Apr 03 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.37-1
- Update to 1.0.37

* Wed Mar 28 2018 Josh Stone <jistone@redhat.com> - 1.0.36-1
- Update to 1.0.36

* Mon Mar 26 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.35-1
- Update to 1.0.35

* Thu Mar 22 2018 Josh Stone <jistone@redhat.com> - 1.0.34-1
- Update to 1.0.34

* Sat Mar 17 2018 Josh Stone <jistone@redhat.com> - 1.0.33-1
- Update to 1.0.33

* Wed Mar 14 2018 Josh Stone <jistone@redhat.com> - 1.0.32-1
- Update to 1.0.32

* Tue Mar 13 2018 Josh Stone <jistone@redhat.com> - 1.0.30-1
- Update to 1.0.30

* Fri Mar 09 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.29-1
- Update to 1.0.29

* Fri Mar 09 2018 Josh Stone <jistone@redhat.com> - 1.0.28-1
- Update to 1.0.28

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.27-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Mon Jan 08 2018 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.27-2
- Rebuild for rust-packaging v5

* Sun Dec 31 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.27-1
- Update to 1.0.27

* Sun Dec 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.25-1
- Update to 1.0.25

* Wed Dec 13 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.24-1
- Update to 1.0.24

* Thu Nov 30 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.23-1
- Update to 1.0.23

* Fri Nov 17 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.21-1
- Update to 1.0.21

* Mon Nov 13 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.20-1
- Update to 1.0.20

* Wed Nov 08 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.19-1
- Update to 1.0.19

* Sat Jul 01 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.9-1
- Update to 1.0.9

* Thu Jun 15 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 1.0.8-1
- Update to 1.0.8

* Wed Jun 14 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.12-2
- Port to use rust-packaging

* Thu Mar 30 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.12-1
- Update to 0.9.12

* Mon Mar 06 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.11-1
- Update to 0.9.11

* Wed Mar 01 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.10-1
- Update to 0.9.10

* Sat Feb 25 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.9-1
- Update to 0.9.9

* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.8-1
- Update to 0.9.8

* Fri Feb 24 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.7-2
- Use rich dependencies

* Sat Feb 18 2017 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.9.7-1
- Initial package

## END: Generated by rpmautospec
