## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 2;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

# Upstream has no tests.
%bcond_with    tests

%global         srcname     azure-mgmt-recoveryservices
%global         tarball_name     azure_mgmt_recoveryservices

Name:           python-%{srcname}
Version:        4.0.0
Release:        %autorelease
Summary:        Microsoft Azure Recovery Services Client Library for Python
License:        MIT
URL:            https://pypi.org/project/%{srcname}/
Source:         %{pypi_source %{tarball_name} %{version}}

BuildArch:      noarch

Epoch:          1


BuildRequires:  python3-devel

%if %{with tests}
BuildRequires:  python3dist(azure-devtools)
BuildRequires:  python3dist(azure-mgmt-keyvault)
BuildRequires:  python3dist(azure-mgmt-resource)
BuildRequires:  python3dist(azure-sdk-tools)
BuildRequires:  python3dist(pytest)
BuildRequires:  python3dist(pytest-aiohttp)
BuildRequires:  python3dist(python-dotenv)
%endif

%global _description %{expand:
Microsoft Azure Recovery Services Client Library for Python}

%description %{_description}


%package -n python3-%{srcname}
Summary:        %{summary}
Obsoletes:      python3-azure-sdk < 5.0.1
%description -n python3-%{srcname} %{_description}


%prep
%autosetup -n %{tarball_name}-%{version}


%generate_buildrequires
%pyproject_buildrequires -r


%build
%pyproject_wheel


%install
%pyproject_install
%pyproject_save_files -l azure


%check
%pyproject_check_import

%if %{with tests}
%pytest
%endif


# LICENSE missing. Made a PR to fix:
# https://github.com/Azure/azure-sdk-for-python/pull/20178
%files -n python3-%{srcname} -f %{pyproject_files}
%doc README.md CHANGELOG.md


%changelog
## START: Generated by rpmautospec
* Thu Apr 30 2026 Daniel McIlvaney <damcilva@microsoft.com> - 1:4.0.0-2
- test: add initial lock files

* Tue Nov 04 2025 Jeremy Cline <jeremycline@linux.microsoft.com> - 1:4.0.0-1
- Update to v4.0.0

* Thu Oct 30 2025 Jeremy Cline <jeremycline@linux.microsoft.com> - 1:3.1.0-1
- Update to v3.1

* Fri Sep 19 2025 Python Maint <python-maint@redhat.com> - 1:3.0.0-8
- Rebuilt for Python 3.14.0rc3 bytecode

* Fri Aug 15 2025 Python Maint <python-maint@redhat.com> - 1:3.0.0-7
- Rebuilt for Python 3.14.0rc2 bytecode

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1:3.0.0-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Tue Jun 03 2025 Python Maint <python-maint@redhat.com> - 1:3.0.0-5
- Rebuilt for Python 3.14

* Sat Jan 18 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1:3.0.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1:3.0.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Sat Jun 08 2024 Python Maint <python-maint@redhat.com> - 1:3.0.0-2
- Rebuilt for Python 3.13

* Tue May 07 2024 Jeremy Cline <jeremycline@microsoft.com> - 1:3.0.0-1
- Bump to version 3.0.0

* Fri Jan 26 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1:2.5.0-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Sun Jan 21 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1:2.5.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Wed Oct 25 2023 Major Hayden <major@redhat.com> - 1:2.5.0-2
- Update to 2.5.0 rhbz#2240840

* Wed Oct 25 2023 Major Hayden <major@redhat.com> - 1:2.5.0-1
- Switch source in pypi to tarball

* Fri Jul 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1:2.4.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Thu Jul 06 2023 Major Hayden <major@redhat.com> - 1:2.4.0-1
- Update to 2.4.0 rhbz#2219715

* Thu Jun 29 2023 Python Maint <python-maint@redhat.com> - 1:2.2.0-3
- Rebuilt for Python 3.12

* Mon May 08 2023 Major Hayden <major@redhat.com> - 1:2.2.0-2
- S

* Fri Feb 10 2023 Major Hayden <major@redhat.com> - 1:2.2.0-1
- Update to 2.2.0

* Fri Jan 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1:2.1.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Wed Sep 07 2022 Major Hayden <major@redhat.com> - 1:2.1.0-1
- Update to 2.1.0

* Fri Jul 22 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1:2.0.0-9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Wed Jun 22 2022 Major Hayden <major@redhat.com> - 1:2.0.0-8
- Add import check

* Wed Jun 15 2022 Python Maint <python-maint@redhat.com> - 1:2.0.0-7
- Rebuilt for Python 3.11

* Tue May 17 2022 Major Hayden <major@mhtx.net> - 1:2.0.0-6
- Add python-dotenv to test reqs

* Fri Apr 29 2022 Major Hayden <major@mhtx.net> - 1:2.0.0-5
- Disable tests in EPEL 9

* Thu Apr 28 2022 Major Hayden <major@mhtx.net> - 1:2.0.0-4
- Switch to rpmautospec

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 1:2.0.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Wed Sep 08 2021 Major Hayden <major@mhtx.net> - 1:2.0.0-2
- Move obsoletes into subpackage

* Mon Aug 09 2021 Major Hayden <major@mhtx.net> - 1:2.0.0-1
- Update to 2.0.0

* Mon Jul 26 2021 Major Hayden <major@mhtx.net> - 1:1.0.0-3
- 🤦 Add sources

* Mon Jul 26 2021 Major Hayden <major@mhtx.net> - 1:1.0.0-2
- Bump release number

* Mon Jul 26 2021 Major Hayden <major@mhtx.net> - 1:1.0.0-1
- Add epoch number for 1.0.0 downgrade

* Fri Jul 23 2021 Fedora Release Engineering <releng@fedoraproject.org> - 2.0.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Tue Jul 20 2021 Major Hayden <major@mhtx.net> - 2.0.0-1
- Update to 2.0.0

* Sat Jul 03 2021 Major Hayden <major@mhtx.net> - 1.0.0-1
- Initial import (#1971847)
## END: Generated by rpmautospec
