.TH SGML.CONF 5
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
sgml.conf \- basic configuration file for SGML environment variables

.SH "DESCRIPTION"
This file contains basic variables for SGML environment.
.HP
Format of this file is straightforward:

- Lines are either empty lines, comment lines (starting with hash mark) or variable assignments.

- Assigments take form of "variable=value" where whitespace is not allowed. This makes the format Bourne-shell includable.

.SH "VARIABLES"
.TP
.B SGML_BASE_DIR
This variable contains root of the location of sgml components. Suggested value for this variable is /usr/share/sgml.
.TP
.B SGML_CATALOGS_DIRS
This variable contains location of sgml catalog files. Suggested value is /etc/sgml.
.TP
.B SGML_EXTRA_BASE_DIRS
This variable contains the directory name(s) of the root of the location(s) of optional sgml components that the system administrator doesn't want to install to primary SGML_BASE_DIR directory. If multiple directory names are mentioned, they are separated by colons.
.TP
.B SGML_BIN_DIR
This variable contains the directory where executables should be placed. By default /usr/bin.
.TP
.B SGML_EXTRA_BIN_DIRS
This variable contains the directory name(s) where optional executables can be placed. Suggested and default value is /usr/local/bin. If multiple directory names are mentioned, they are separated by colons.
.TP
.B SGML_TMP_DIR
A hint to components where to put temporary files. The suggested and default value is /tmp.
.TP
.B SGML_POSTINSTALL_CMD
A command that is to be executed when new components have been installed. This mechanism is not used by default, sgml components are usually registered by %post scriptlets.
.SH "SEE ALSO"
.\" Always quote multiple words for .SH
.BR xsltproc (1)
