## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 3;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

%global tarball_version %%(echo %{version} | tr '~' '.')

Name:           libpanel
Version:        1.10.3
Release:        %autorelease
Summary:        IDE paneling library for GTK

License:        LGPL-3.0-or-later
URL:            https://gitlab.gnome.org/GNOME/libpanel
Source0:        https://download.gnome.org/sources/libpanel/1.10/libpanel-%{tarball_version}.tar.xz

BuildRequires:  gcc
BuildRequires:  meson
BuildRequires:  pkgconfig(gi-docgen)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gtk4)
BuildRequires:  pkgconfig(libadwaita-1)

Requires:       hicolor-icon-theme

%description
libpanel is a collection of GTK widgets for IDE-like applications targeting
GNOME using GTK and libadwaita.


%package        devel
Summary:        Development files for %{name}
Requires:       %{name}%{?_isa} = %{version}-%{release}
# Because web fonts from upstream are not bundled in the gi-docgen package,
# packages containing documentation generated with gi-docgen should depend on
# this metapackage to ensure the proper system fonts are present.
Recommends:     gi-docgen-fonts

%description    devel
The %{name}-devel package contains libraries and header files for
developing applications that use %{name}.


%prep
%autosetup -p1 -n libpanel-%{tarball_version}


%build
%meson
%meson_build


%install
%meson_install

%find_lang libpanel


%files -f libpanel.lang
%license COPYING
%doc AUTHORS NEWS README.md
%{_libdir}/libpanel-1.so.1*
%dir %{_libdir}/girepository-1.0
%{_libdir}/girepository-1.0/Panel-1.typelib
%{_datadir}/icons/hicolor/scalable/actions/panel-*-symbolic.svg

%files devel
%{_includedir}/libpanel-1/
%{_libdir}/libpanel-1.so
%{_libdir}/pkgconfig/libpanel-1.pc
%dir %{_datadir}/gir-1.0
%{_datadir}/gir-1.0/Panel-1.gir
%dir %{_datadir}/vala
%dir %{_datadir}/vala/vapi
%{_datadir}/vala/vapi/libpanel-1.deps
%{_datadir}/vala/vapi/libpanel-1.vapi
%doc %{_datadir}/doc/panel-1.0/


%changelog
## START: Generated by rpmautospec
* Mon Apr 06 2026 azldev <> - 1.10.3-3
- Latest state for libpanel

* Fri Dec 05 2025 Benjamin A. Beasley <code@musicinmybrain.net> - 1.10.3-2
- Ensure correct fonts are installed for HTML docs

* Fri Oct 31 2025 Matthias Clasen <mclasen@redhat.com> - 1.10.3-1
- 1.10.3

* Mon Sep 15 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 1.10.2-1
- Update to 1.10.2

* Thu Sep 04 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 1.10.1-1
- Update to 1.10.1

* Thu Jul 24 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.10.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Mon Mar 17 2025 nmontero <nmontero@redhat.com> - 1.10.0-1
- Update to 1.10.0

* Mon Feb 03 2025 nmontero <nmontero@redhat.com> - 1.9.0-1
- Update to 1.9.0

* Fri Jan 17 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.8.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Sat Oct 19 2024 David King <amigadave@amigadave.com> - 1.8.1-1
- Update to 1.8.1

* Wed Sep 18 2024 nmontero <nmontero@redhat.com> - 1.8.0-1
- Update to 1.8.0

* Mon Aug 05 2024 nmontero <nmontero@redhat.com> - 1.7.1-1
- Update to 1.7.1

* Thu Jul 18 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.7.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Mon Jul 01 2024 Nieves Montero <nmontero@redhat.com> - 1.7.0-1
- Update to 1.7.0

* Sat Mar 16 2024 David King <amigadave@amigadave.com> - 1.6.0-1
- Update to 1.6.0

* Tue Mar 05 2024 David King <amigadave@amigadave.com> - 1.5.1-1
- Update to 1.5.1 (#2264680)

* Mon Feb 19 2024 David King <amigadave@amigadave.com> - 1.5.0-1
- Update to 1.5.0

* Thu Jan 25 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.4.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Sun Jan 21 2024 Fedora Release Engineering <releng@fedoraproject.org> - 1.4.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Thu Jan 11 2024 Kalev Lember <klember@redhat.com> - 1.4.1-1
- Update to 1.4.1

* Mon Sep 18 2023 Kalev Lember <klember@redhat.com> - 1.4.0-1
- Update to 1.4.0

* Tue Sep 05 2023 Kalev Lember <klember@redhat.com> - 1.3.1-1
- Update to 1.3.1

* Wed Aug 09 2023 Kalev Lember <klember@redhat.com> - 1.3.0-1
- Update to 1.3.0

* Thu Jul 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1.2.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Sun Mar 19 2023 David King <amigadave@amigadave.com> - 1.2.0-1
- Update to 1.2.0

* Sat Mar 04 2023 David King <amigadave@amigadave.com> - 1.1.2-1
- Update to 1.1.2 (#2170280)

* Thu Feb 09 2023 David King <amigadave@amigadave.com> - 1.1.0-1
- Update to 1.1.0

* Thu Jan 19 2023 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Mon Dec 12 2022 Kalev Lember <klember@redhat.com> - 1.0.2-1
- Update to 1.0.2

* Tue Sep 27 2022 Kalev Lember <klember@redhat.com> - 1.0.1-1
- Update to 1.0.1

* Fri Sep 16 2022 Kalev Lember <klember@redhat.com> - 1.0.0-1
- Update to 1.0.0
- Build devel documentation
- Include translations

* Mon Sep 05 2022 Kalev Lember <klember@redhat.com> - 1.0~alpha1-2
- Move icons to the base package

* Mon Aug 08 2022 Kalev Lember <klember@redhat.com> - 1.0~alpha1-1
- Update to 1.0.alpha1

* Fri Jul 29 2022 Kalev Lember <klember@redhat.com> - 1.0~alpha-2
- Add hicolor-icon-theme requires

* Fri Jul 29 2022 Kalev Lember <klember@redhat.com> - 1.0~alpha-1
- Initial Fedora packaging
## END: Generated by rpmautospec
