## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 5;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate derive_more

Name:           rust-derive_more
Version:        2.0.1
Release:        %autorelease
Summary:        Adds #[derive(x)] macros for more traits

License:        MIT
URL:            https://crates.io/crates/derive_more
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Adds #[derive(x)] macros for more traits.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+add-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+add-devel %{_description}

This package contains library source intended for building other packages which
use the "add" feature of the "%{crate}" crate.

%files       -n %{name}+add-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+add_assign-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+add_assign-devel %{_description}

This package contains library source intended for building other packages which
use the "add_assign" feature of the "%{crate}" crate.

%files       -n %{name}+add_assign-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+as_ref-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+as_ref-devel %{_description}

This package contains library source intended for building other packages which
use the "as_ref" feature of the "%{crate}" crate.

%files       -n %{name}+as_ref-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+constructor-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+constructor-devel %{_description}

This package contains library source intended for building other packages which
use the "constructor" feature of the "%{crate}" crate.

%files       -n %{name}+constructor-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deref-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deref-devel %{_description}

This package contains library source intended for building other packages which
use the "deref" feature of the "%{crate}" crate.

%files       -n %{name}+deref-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+deref_mut-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+deref_mut-devel %{_description}

This package contains library source intended for building other packages which
use the "deref_mut" feature of the "%{crate}" crate.

%files       -n %{name}+deref_mut-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+display-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+display-devel %{_description}

This package contains library source intended for building other packages which
use the "display" feature of the "%{crate}" crate.

%files       -n %{name}+display-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+error-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+error-devel %{_description}

This package contains library source intended for building other packages which
use the "error" feature of the "%{crate}" crate.

%files       -n %{name}+error-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+from-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+from-devel %{_description}

This package contains library source intended for building other packages which
use the "from" feature of the "%{crate}" crate.

%files       -n %{name}+from-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+from_str-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+from_str-devel %{_description}

This package contains library source intended for building other packages which
use the "from_str" feature of the "%{crate}" crate.

%files       -n %{name}+from_str-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+full-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+full-devel %{_description}

This package contains library source intended for building other packages which
use the "full" feature of the "%{crate}" crate.

%files       -n %{name}+full-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+index-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+index-devel %{_description}

This package contains library source intended for building other packages which
use the "index" feature of the "%{crate}" crate.

%files       -n %{name}+index-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+index_mut-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+index_mut-devel %{_description}

This package contains library source intended for building other packages which
use the "index_mut" feature of the "%{crate}" crate.

%files       -n %{name}+index_mut-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+into-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+into-devel %{_description}

This package contains library source intended for building other packages which
use the "into" feature of the "%{crate}" crate.

%files       -n %{name}+into-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+into_iterator-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+into_iterator-devel %{_description}

This package contains library source intended for building other packages which
use the "into_iterator" feature of the "%{crate}" crate.

%files       -n %{name}+into_iterator-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+is_variant-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+is_variant-devel %{_description}

This package contains library source intended for building other packages which
use the "is_variant" feature of the "%{crate}" crate.

%files       -n %{name}+is_variant-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mul-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mul-devel %{_description}

This package contains library source intended for building other packages which
use the "mul" feature of the "%{crate}" crate.

%files       -n %{name}+mul-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mul_assign-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mul_assign-devel %{_description}

This package contains library source intended for building other packages which
use the "mul_assign" feature of the "%{crate}" crate.

%files       -n %{name}+mul_assign-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+not-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+not-devel %{_description}

This package contains library source intended for building other packages which
use the "not" feature of the "%{crate}" crate.

%files       -n %{name}+not-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sum-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sum-devel %{_description}

This package contains library source intended for building other packages which
use the "sum" feature of the "%{crate}" crate.

%files       -n %{name}+sum-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+testing-helpers-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+testing-helpers-devel %{_description}

This package contains library source intended for building other packages which
use the "testing-helpers" feature of the "%{crate}" crate.

%files       -n %{name}+testing-helpers-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+try_from-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+try_from-devel %{_description}

This package contains library source intended for building other packages which
use the "try_from" feature of the "%{crate}" crate.

%files       -n %{name}+try_from-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+try_into-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+try_into-devel %{_description}

This package contains library source intended for building other packages which
use the "try_into" feature of the "%{crate}" crate.

%files       -n %{name}+try_into-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+try_unwrap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+try_unwrap-devel %{_description}

This package contains library source intended for building other packages which
use the "try_unwrap" feature of the "%{crate}" crate.

%files       -n %{name}+try_unwrap-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unwrap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unwrap-devel %{_description}

This package contains library source intended for building other packages which
use the "unwrap" feature of the "%{crate}" crate.

%files       -n %{name}+unwrap-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -a

%build
%cargo_build -a

%install
%cargo_install -a

%if %{with check}
%check
# * skip trybuild tests that fail due to missing test fixtures
# * skip three tests that fail on big-endian architectures:
#   https://github.com/JelteF/derive_more/issues/451
%cargo_test -a -- -- --exact --skip compile_fail --skip "structs::multi_field::r#unsized::assert" --skip "structs::multi_field::r#unsized::interpolated::assert" --skip "structs::multi_field::r#unsized::interpolated::assert"
%endif

%changelog
## START: Generated by rpmautospec
* Wed Apr 22 2026 azldev <azurelinux@microsoft.com> - 2.0.1-5
- Latest state for rust-derive_more

* Sat Jan 17 2026 Fedora Release Engineering <releng@fedoraproject.org> - 2.0.1-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 2.0.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Tue Mar 25 2025 Fabio Valentini <decathorpe@gmail.com> - 2.0.1-2
- Skip three tests that fail on big-endian architectures

* Sat Mar 22 2025 Fabio Valentini <decathorpe@gmail.com> - 2.0.1-1
- Update to version 2.0.1; Fixes RHBZ#2343601

* Sun Jan 19 2025 Fedora Release Engineering <releng@fedoraproject.org> - 1.0.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Mon Sep 02 2024 Fabio Valentini <decathorpe@gmail.com> - 1.0.0-1
- Update to version 1.0.0; Fixes RHBZ#2303544

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.17-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Fri Jan 26 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.17-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Sat Aug 05 2023 Fabio Valentini <decathorpe@gmail.com> - 0.99.17-6
- Regenerate with rust2rpm v24

* Fri Jul 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.17-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Fri Jan 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.17-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Sat Jul 23 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.17-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.17-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Tue Nov 30 2021 Fabio Valentini <decathorpe@gmail.com> - 0.99.17-1
- Update to version 0.99.17; Fixes RHBZ#2027108

* Fri Jul 09 2021 Fabio Valentini <decathorpe@gmail.com> - 0.99.16-1
- Update to version 0.99.16; Fixes RHBZ#1980159

* Sun May 23 2021 Fabio Valentini <decathorpe@gmail.com> - 0.99.14-1
- Update to version 0.99.14.
- Fixes RHBZ#1960922

* Mon May 10 2021 Fabio Valentini <decathorpe@gmail.com> - 0.99.13-1
- Update to version 0.99.13.

* Mon Mar 29 18:05:23 CEST 2021 Robert-André Mauchin <zebob.m@gmail.com> - 0.99.11-3
- Bump rustc_version to 0.3

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.11-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Thu Oct 01 2020 Fabio Valentini <decathorpe@gmail.com> - 0.99.11-1
- Update to version 0.99.11.

* Fri Sep 11 2020 Josh Stone <jistone@redhat.com> - 0.99.10-1
- Update to 0.99.10

* Sat Aug 01 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.9-3
- Second attempt - Rebuilt for
  https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.9-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Jul 10 2020 Josh Stone <jistone@redhat.com> - 0.99.9-1
- Update to 0.99.9

* Fri Jun 19 2020 Josh Stone <jistone@redhat.com> - 0.99.8-1
- Update to 0.99.8

* Sat May 16 19:40:36 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.99.7-1
- Update to 0.99.7

* Thu May 14 2020 Josh Stone <jistone@redhat.com> - 0.99.6-1
- Update to 0.99.6

* Sun Mar 29 09:48:38 CEST 2020 Igor Raits <ignatenkobrain@fedoraproject.org> - 0.99.5-1
- Update to 0.99.5

* Thu Feb 20 2020 Josh Stone <jistone@redhat.com> - 0.99.3-1
- Update to 0.99.3

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.99.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Sat Dec 14 00:21:58 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.99.2-1
- Update to 0.99.2

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.15.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Jun 18 09:56:43 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.15.0-1
- Update to 0.15.0

* Thu May 30 18:33:43 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.14.1-1
- Initial package

## END: Generated by rpmautospec
