## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 3;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

Name:           python-parso
Version:        0.8.5
Release:        %autorelease
Summary:        Parser that supports error recovery and round-trip parsing
License:        MIT AND PSF-2.0
BuildArch:      noarch
URL:            https://github.com/davidhalter/parso
Source:         %{pypi_source parso}

%global common_description %{expand:
Parso is a Python parser that supports error recovery and round-trip parsing
for different Python versions (in multiple Python versions). Parso is also able
to list multiple syntax errors in your python file.  Parso has been
battle-tested by jedi. It was pulled out of jedi to be useful for other
projects as well.  Parso consists of a small API to parse Python and analyse
the syntax tree.}


%description %{common_description}


%package -n python3-parso
Summary:        %{summary}
BuildRequires:  python3-devel


%description -n python3-parso %{common_description}


%prep
%autosetup -p 1 -n parso-%{version}

sed -e '/^addopts/d' -i pytest.ini

# Upstream maintains grammar files for individual Python versions.
# To ease testing with the next Python version, we copy the previous grammar
# if the current one is not found.
# If this doesn't work, the tests should fail.
cd parso/python
%global python3_version_nodots_previous %[0%{?python3_version_nodots} - 1]
if [[ ! -f grammar%{python3_version_nodots}.txt &&
        -f grammar%{python3_version_nodots_previous}.txt ]]; then
  cp -a grammar%{python3_version_nodots_previous}.txt grammar%{python3_version_nodots}.txt
fi
cd -


%generate_buildrequires
%pyproject_buildrequires -x testing


%build
%pyproject_wheel


%install
%pyproject_install
%pyproject_save_files parso


%check
# According to upstream, the error tests are "very susceptible to failures and
# might break from time to time".  They recommend skipping them during distro
# package builds.
# https://github.com/davidhalter/parso/issues/63
# https://github.com/davidhalter/parso/issues/103
# https://github.com/davidhalter/parso/issues/123
# https://bugzilla.redhat.com/show_bug.cgi?id=1830965
# https://github.com/davidhalter/parso/issues/192
# https://github.com/davidhalter/parso/issues/222
%pytest --verbose -k "not test_python_exception_matches"


%files -n python3-parso -f %{pyproject_files}
%doc README.rst


%changelog
## START: Generated by rpmautospec
* Thu Apr 30 2026 Daniel McIlvaney <damcilva@microsoft.com> - 0.8.5-3
- test: add initial lock files

* Fri Sep 19 2025 Python Maint <python-maint@redhat.com> - 0.8.5-2
- Rebuilt for Python 3.14.0rc3 bytecode

* Sat Sep 13 2025 Romain Geissler <romain.geissler@amadeus.com> - 0.8.5-1
- Update to version 0.8.5 rhbz#2390527

* Fri Aug 15 2025 Python Maint <python-maint@redhat.com> - 0.8.4-9
- Rebuilt for Python 3.14.0rc2 bytecode

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.4-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Mon Jun 02 2025 Python Maint <python-maint@redhat.com> - 0.8.4-7
- Rebuilt for Python 3.14

* Thu Feb 27 2025 Carl George <carlwgeorge@fedoraproject.org> - 0.8.4-6
- Add patch for Python 3.14 compatibility rhbz#2325187

* Sat Jan 18 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.4-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.4-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Fri Jun 07 2024 Python Maint <python-maint@redhat.com> - 0.8.4-2
- Rebuilt for Python 3.13

* Thu Jun 06 2024 Carl George <carlwgeorge@fedoraproject.org> - 0.8.4-1
- Update to version 0.8.4 rhbz#2273616
- Switch to SPDX license notation

* Thu Mar 07 2024 Carl George <carlwgeorge@fedoraproject.org> - 0.8.3-10
- Add patch for Python 3.13 compatibility rhbz#2246284

* Fri Jan 26 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.3-9
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Mon Jan 22 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.3-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Fri Jul 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.3-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Tue Jun 13 2023 Python Maint <python-maint@redhat.com> - 0.8.3-6
- Rebuilt for Python 3.12

* Fri Jan 20 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.3-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_38_Mass_Rebuild

* Fri Jul 22 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.3-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Mon Jun 13 2022 Python Maint <python-maint@redhat.com> - 0.8.3-3
- Rebuilt for Python 3.11

* Mon Apr 25 2022 Carl George <carl@george.computer> - 0.8.3-2
- Remove upstream pytest addopts
- Resolves: rhbz#2078414

* Fri Apr 08 2022 Carl George <carl@george.computer> - 0.8.3-1
- Latest upstream
- Resolves: rhbz#2027862

* Fri Jan 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.2^1.da3a748-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Tue Sep 21 2021 Carl George <carl@george.computer> - 0.8.2^1.da3a748-1
- Latest upstream snapshot
- Resolves: rhbz#1906491
- Resolves: rhbz#1987878

* Fri Jul 23 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-5
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Wed Jun 02 2021 Python Maint <python-maint@redhat.com> - 0.8.0-4
- Rebuilt for Python 3.10

* Wed Jan 27 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_34_Mass_Rebuild

* Fri Nov 06 2020 Carl George <carl@george.computer> - 0.8.0-2
- Rebuild

* Wed Sep 09 2020 Charalampos Stratakis <cstratak@redhat.com> - 0.8.0-1
- Update to 0.8.0 (rhbz#1860194)

* Wed Jul 29 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_33_Mass_Rebuild

* Fri Jul 10 2020 Mukundan Ragavan <nonamedotc@fedoraproject.org> - 0.7.0-1
- Update to 0.7.0

* Sun May 24 2020 Miro Hrončok <mhroncok@redhat.com> - 0.6.2-2
- Rebuilt for Python 3.9

* Tue Mar 17 2020 Carl George <carl@george.computer> - 0.6.2-1
- Latest upstream
- Add patch0 to fix test suite on Python 3.8.2

* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Jan 06 2020 Carl George <carl@george.computer> - 0.5.2-1
- Latest upstream

* Thu Oct 17 2019 Carl George <carl@george.computer> - 0.5.1-4
- Run tests on el8

* Thu Oct 03 2019 Miro Hrončok <mhroncok@redhat.com> - 0.5.1-3
- Rebuilt for Python 3.8.0rc1 (#1748018)

* Thu Aug 15 2019 Miro Hrončok <mhroncok@redhat.com> - 0.5.1-2
- Rebuilt for Python 3.8

* Fri Jul 26 2019 Carl George <carl@george.computer> - 0.5.1-1
- Latest upstream
- Drop EPEL python34 subpackage
- Disable python2 package on F31+ and EL8+ rhbz#1733248

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.5.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Tue Jun 25 2019 Carl George <carl@george.computer> - 0.5.0-1
- Latest upstream

* Mon Apr 08 2019 Carl George <carl@george.computer> - 0.4.0-1
- Latest upstream rhbz#1668959
- Don't use common documentation directory between subpackages

* Sat Feb 02 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild

* Wed Aug 08 2018 Carl George <carl@george.computer> - 0.3.1-1
- Latest upstream
- Use common documentation directory
- Enable python36 subpackage for EPEL

* Sat Jul 14 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.2.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild

* Fri Jun 15 2018 Miro Hrončok <mhroncok@redhat.com> - 0.2.1-2
- Rebuilt for Python 3.7

* Mon May 21 2018 Carl George <carl@george.computer> - 0.2.1-1
- Latest upstream

* Mon Apr 16 2018 Carl George <carl@george.computer> - 0.2.0-1
- Latest upstream

* Fri Feb 09 2018 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild

* Sat Dec 30 2017 Carl George <carl@george.computer> - 0.1.1-2
- Be more explicit with the files in site-packages

* Tue Dec 26 2017 Carl George <carl@george.computer> - 0.1.1-1
- Initial package

## END: Generated by rpmautospec
