.TH GRPC_CLI\-TYPE "1" "May 2021" "" "User Commands"
.SH NAME
.B grpc_cli\ type
\(en print type
.SH SYNOPSIS
.B grpc_cli type
.I address
.I type
.RI [ OPTION ]...\:
.SH OPTIONS
.TP
.I address
.IB host : port
.TP
.I type
Protocol buffer type name
.TP
.B \-\-ssl_target
Set server host for ssl validation
.TP
.B \-\-ssl_client_cert
Client cert for ssl
.TP
.B \-\-ssl_client_key
Client private key for ssl
.TP
.B \-\-local_connect_type
Set to
.B local_tcp
or
.B uds
.TP
.B \-\-channel_creds_type
Set to
.BR insecure ,
.BR ssl ,
.BR gdc ,
.BR alts ,
or
.B local
.TP
.B \-\-call_creds
Set to
.BR none ,
or
.BI access_token= token
.SH "SEE\ ALSO"
.BR grpc_cli (1),
.BR grpc_cli\-ls (1),
.BR grpc_cli\-call (1),
.BR grpc_cli\-parse (1),
.BR grpc_cli\-totext (1),
.BR grpc_cli\-tojson (1),
.BR grpc_cli\-tobinary (1),
.BR grpc_cli\-help (1)
