--- ./Makefile	2021-04-06 08:53:18.554954462 -0700
+++ ./Makefile	2021-04-14 09:44:09.424948057 -0700
@@ -70,7 +70,7 @@
 cppcheck:
 	cppcheck --force -q --enable=performance --enable=warning --enable=portability *.h *.c
 
-install: install-man install-shared install-includes
+install: install-man install-static install-includes
 
 install-man:
 	install -d -m 0755 $(DESTDIR)$(PREFIX)/share/man/man3
