.TH HATCHLING\-METADATA "1" "October 2022" "" "User Commands"
.SH NAME
.B hatchling\ metadata
.SH SYNOPSIS
.B hatchling\ metadata
.RB [ \-h ]
.RB [ \-c ]
.RI [ field ]
.SH OPTIONS
.SS "POSITIONAL\ ARGUMENTS"
.TP
.I field
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit
.TP
.B \-c\fR,\ \fB\-\-compact
.SH "SEE\ ALSO"
.BR hatchling\-build (1),
.BR hatchling\-dep (1),
.BR hatchling\-version (1)
.P
.BR hatchling (1)
