# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG BASE_IMAGE

FROM $BASE_IMAGE

@INCLUDE_MAIN_RUN_INSTRUCTION@

# basic smoke test
RUN prometheus --version

# set default command for the container
CMD ["prometheus", "--config.file=/etc/prometheus/prometheus.yml"]
