.TH pam_krb5 5 2014/02/11 "Red Hat Linux" "System Administrator's Manual"

.SH NAME
pam_krb5 \- Kerberos 5 authentication

.SH DESCRIPTION
pam_krb5.so reads its configuration information from the \fBappdefaults\fR
section of \fBkrb5.conf\fR(5).  You should read the \fBkrb5.conf\fR(5) man page
before continuing here.  The module expects its configuration information to be
in the \fBpam\fR subsection of the \fBappdefaults\fR section.

.SH DIRECTIVES
Directives which take a \fItrue\fR, \fIfalse\fR, or a PAM service name can also
be selectively disabled for specific PAM services using the related "no_"
option (exceptions to "debug = true" can be made using "no_debug", for example).

.IP "debug = \fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
turns on debugging via \fBsyslog\fR(3).  Debug messages are logged with
priority \fILOG_DEBUG\fR.

.IP "debug_sensitive = \fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
turns on debugging of sensitive information via \fBsyslog\fR(3).  Debug
messages are logged with priority \fILOG_DEBUG\fR.

.IP "afs_cells = \fIcell.example.com [...]\fR"
tells pam_krb5.so to obtain tokens for the listed cells,
in addition to the local cell and the cell which
contains the user's home directory, for the user.
The module will guess the principal name of the AFS
service for the listed cells, or it can be specified by listing cells
in the form \fIcellname\fB=principalname\fR.

.IP "always_allow_localname = \fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
tells pam_krb5.so, when performing an authorization check using the
target user's .k5login file, to always allow access when the
principal name being authenticated maps to the local user's name
(as configured using the \fIauth_to_local_names\fR and
\fIauth_to_local\fR settings in \fBkrb5.conf\fR(5), if your
implementation provides those settings).  Otherwise, if the file
exists and can be read, but the principal is not explicitly listed,
access is typically denied.  This setting is disabled by default.

.IP "armor = \fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
attempt to use armoring when communicating with the KDC.
This option is currently mainly only useful for testing, as the
\fIkeytab\fR method should not be expected to work when the module
is called from an unprivileged process, and the \fIpkinit\fR
method requires that the KDC is properly configured
to offer anonymous PKINIT, and that the client is also properly
configured to trust the KDC's CA.
The default is \fBfalse\fR.

.IP "armor_strategy = \fIkeytab,pkinit\fR"
controls how the module will attempt to obtain tickets for use as
armor. The value should be a comma-separated list of methods.
Supported methods include \fIketyab\fR and \fIpkinit\fR.
The default is \fBkeytab,pkinit\fR.

.IP "banner = \fIKerberos 5\fR"
specifies what sort of password the module claims to be changing whenever it is
called upon to change passwords.  The default is \fBKerberos 5\fR.

.IP "ccache_dir = \fI/var/tmp\fR"
specifies the directory in which to place credential cache files.  The default
is \fI/tmp\fR.

.IP "ccname_template = \fIKEYRING:krb5cc_%U_%P\fR"
.IP "ccname_template = \fIFILE:%d/krb5cc_%U_XXXXXX\fR"
specifies the location in which to place the user's session-specific
credential cache.  This value is treated as a template, and these sequences
are substituted:
  %u	login name
  %U	login UID
  %p	principal name
  %r	principal's realm name
  %h	home directory
  %d	the default ccache directory (as set with \fIccache_dir\fR)
  %P	the current process ID
  %%	literal '%'

If the resulting template does not end with "XXXXXX", a suffix will be added to
the configured value.
If not set, the module attempts to read the default
used by libkrb5 from \fBkrb5.conf\fP(5), and if one
is not found, the default is
\fIFILE:%d/krb5cc_%U_XXXXXX\fR".
.\" The default is \fIFILE:%d/krb5cc_%U_XXXXXX\fR".

.IP "chpw_prompt = \fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
tells pam_krb5.so to allow expired passwords to be changed during
authentication attempts.  While this is the traditional behavior exhibited by
"kinit", it is inconsistent with the behavior expected by PAM, which expects
authentication to (appear to) succeed, only to have password expiration be
flagged by a subsequent call to the account management function.  Some
applications which don't handle password expiration correctly will fail
unconditionally if the user's password is expired, and this flag can be used
to attempt to work around this bug in those applications.
The default is \fBfalse\fR.

.IP "cred_session=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
specifies that pam_krb5 should create and destroy credential caches, as it
does when the calling application opens and closes a PAM session, when the
calling application establishes and deletes PAM credentials.  This is done
to compensate for applications which expect to create a credential cache but
which don't use PAM session management.  It is usually a harmless redundancy
in applications which don't require it, so this option is enabled by default
except for this list of services: "\fIsshd\fR".

.IP "external = \fItrue\fR|\fIfalse\fR|\fIsshd ftp [...]\fR"
tells pam_krb5.so to use Kerberos credentials provided by the calling
application during session setup.
This is most often useful for obtaining AFS tokens.
The default is "\fIsshd\fR".

.IP "ignore_afs=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
tells pam_krb5.so to completely ignore the presence of AFS, preventing
any attempts to obtain new tokens on behalf of the calling application.

.IP "ignore_k5login=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
specifies which other not pam_krb5 should skip checking the user's .k5login
file to verify that the principal name of the client being authenticated is
authorized to access the user account.  (Actually, the check is performed by
a function offered by the Kerberos library, which controls which files it
will consult.)  The default is \fIfalse\fR, which causes pam_krb5 to perform
the check.

.IP "ignore_unknown_principals=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
.IP "ignore_unknown_spn=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
.IP "ignore_unknown_upn=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
specifies which other not pam_krb5 should return a PAM_IGNORE code to libpam
instead of PAM_USER_UNKNOWN for users for whom the determined principal name
is expired or does not exist.

.IP "initial_prompt=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
tells pam_krb5.so whether or not to ask for a password before attempting
authentication.  If one is needed and pam_krb5.so has not prompted for it, the
Kerberos library should trigger a request for a password.

.IP "keytab = \fIFILE:/etc/krb5.keytab\fR
.IP "keytab = \fIFILE:/etc/krb5.keytab imap=FILE:/etc/imap.keytab\fR"
specifies the name of a keytab file to search for a service key for use
in validating TGTs.  The location can be specified on a per-service basis
by specifying a list of locations in the form \fIpam_service\fR=\fIlocation\fR.
The default is \fIFILE:/etc/krb5.keytab\fR.

.IP "mappings = \fIregex1 regex2 [...]\fR"
specifies that pam_krb5 should derive the user's principal name from the Unix
user name by first checking if the user name matches \fBregex1\fR, and
formulating a principal name using \fBregex2\fR.  For example,
\fB"mappings = ^EXAMPLE\e\e(.*)$ $1@EXAMPLE.COM\fR"
would map any user with a name of the form "EXAMPLE\ewhatever" to a principal
name of "whatever@EXAMPLE.COM".  This is primarily targeted at allowing
pam_krb5 to be used to authenticate users whose user information is provided by
\fBwinbindd\fP(8).  This will frequently require the reverse to be configured by
setting up an auth_to_local rule elsewhere in \fBkrb5.conf\fP(5).

.IP "minimum_uid = \fI0\fR"
specifies the minimum UID of users being authenticated.  If a user with a UID
less than this value attempts authentication, the request will be ignored.

.IP "multiple_ccaches=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
specifies that pam_krb5 should maintain multiple credential caches for
applications that both set credentials and open a PAM session, but which set
the KRB5CCNAME variable after doing only one of the two.  This option is
usually not necessary for most services.

.\" .IP "pkinit_flags = \fI0\fR"
.\" controls the flags value which pam_krb5 passes to libkrb5
.\" when setting up PKINIT parameters.  This is useful mainly for
.\" debugging.
.\" 
.\" .IP "pkinit_identity = \fI\fR"
.\" controls where pam_krb5 instructs libkrb5 to search for the
.\" user's private key and certificate, so that the client can be
.\" authenticated using PKINIT, if the KDC supports it.  This value
.\" is treated as a template, and these sequences are substituted:
.\"   %u	login name
.\"   %U	login UID
.\"   %p	principal name
.\"   %r	principal's realm name
.\"   %h	home directory
.\"   %d	the default ccache directory (as set with \fIccache_dir\fR)
.\"   %P	the current process ID
.\"   %%	literal '%'
.\" .br
.\" Other PKINIT-specific defaults, such as the locations of trust
.\" anchors, can be set in krb5.conf(5).
.\" 
.IP "preauth_options = \fI\fR"
controls the preauthentication options which pam_krb5 passes
to libkrb5, if the system-defaults need to be overridden.
The list is treated as a template, and these sequences are
substituted:

  %u	login name
  %U	login UID
  %p	principal name
  %r	principal's realm name
  %h	home directory
  %d	the default ccache directory (as set with \fIccache_dir\fR)
  %P	the current process ID
  %%	literal '%'

A list of recognized values should be listed in the kinit(1)
manual page as parameters for its -X option.

.IP "null_afs=\fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
tells pam_krb5.so, when it attempts to set tokens, to try to get
credentials for services with names which resemble afs@\fIREALM\fR
before attempting to get credentials for services with names resembling
afs/\fIcell\fR@\fIREALM\fR.  The default is to assume that the cell's
name is the instance in the AFS service's Kerberos principal name.

.IP "pwhelp = \fIfilename\fR"
specifies the name of a text file whose contents will be displayed to
clients who attempt to change their passwords.  There is no default.

.IP "subsequent_prompt = \fItrue\fR|\fIfalse\fR|\fIservice\ [...]\fR"
controls whether or not pam_krb5.so will allow the Kerberos library to ask
the user for a password or other information, if the previously-entered
password is somehow insufficient for authenticating the user.  This is
commonly needed to allow a user to log in when that user's password has
expired.  The default is \fBfalse\fR during password changes, and
\fBtrue\fR otherwise.

If the calling application does not properly support PAM conversations
(possibly due to limitations of a network protocol which it is serving),
this may be need to be disabled for that application to prevent it
from supplying the user's current password in a password-changing
situation when a new password is called for.

.IP "tokens = \fItrue\fR|\fIfalse\fR|\fIservice\ [...]\fR"
signals that pam_krb5.so should create an AFS PAG and obtain tokens
during authentication in addition to session setup.  This is primarily
useful in server applications which need to access a user's files but
which do not open PAM sessions before doing so.  For correctly-written
applications, this flag is not necessary.

.IP "token_strategy = \fIrxk5,2b[,...]\fR"
controls how, and using which format, pam_krb5.so should attempt to
set AFS tokens for the user's session.
By default, the module is configured with
"token_strategy = \fI2b\fR".
Recognized strategy names include:
 \fIrxk5\fP  rxk5 (requires OpenAFS 1.6 or later)
 \fI2b\fP    rxkad "2b" (requires OpenAFS 1.2.8 or later)

.IP "trace = \fItrue\fR|\fIfalse\fR|\fIservice [...]\fR"
turns on libkrb5's library tracing.  Trace messages are
logged to \fBsyslog\fR(3) with priority \fILOG_DEBUG\fR.

.IP "use_shmem = \fItrue\fR|\fIfalse\fR|\fIservice\ [...]\fR"
tells pam_krb5.so to pass credentials from the authentication service function
to the session management service function using shared memory for specific
services.  By default, the module is configured with
"use_shmem = \fIsshd\fR".

.IP "validate = \fItrue\fR|\fIfalse\fR|\fIservice\ [...]\fR"
specifies whether or not to attempt validation of the TGT using the local
keytab.  The default is \fBtrue\fR.
The \fBlibdefaults\fR \fBverify_ap_req_nofail\fR setting can
affect whether or not errors reading the keytab which are encountered during
validation will be suppressed.

.IP "validate_user_user = \fItrue\fR|\fIfalse\fR|\fIservice\ [...]\fR"
specifies whether or not, when attempting validation of the TGT, to attempt
user-to-user authentication using a previously-obtainted TGT in the default
ccache if validation can't be performed using a keytab.  The default is
\fBfalse\fR.

.SH EXAMPLE

[appdefaults]
  pam = {
    validate = true
    ccache_dir = /var/tmp
    external = sshd
    tokens = imap ftpd
    TEST.EXAMPLE.COM = {
      debug = true
      afs_cells = testcell.example.com othercell.example.com
      keytab = FILE:/etc/krb5.keytab httpd=FILE:/etc/httpd.keytab
    }
  }

.SH FILES
\fI/etc/krb5.conf\fR
.br
.SH "SEE ALSO"
.BR pam_krb5 (8)
.br
.SH BUGS
Probably, but let's hope not.  If you find any, please file them in the
bug database at http://bugzilla.redhat.com/ against the "pam_krb5" component.

.SH AUTHOR
Nalin Dahyabhai <nalin@redhat.com>
