[images.vm-base]
description = "VM Base Image"
definition = { type = "kiwi", path = "vm-base/vm-base.kiwi" }

[images.vm-base.tests]
test-suites = [
  { name = "lisa-main" },
  { name = "lisa-xfs" },
  { name = "lisa-perf" },
  { name = "lisa-smoke" },
  { name = "lisa-kernel-ltp" },
]

[images.container-base]
description = "Container Base Image"
definition = { type = "kiwi", path = "container-base/container-base.kiwi", profile = "core" }

[images.container-distroless-minimal]
description = "Container Distroless Minimal Image"
definition = { type = "kiwi", path = "container-base/container-base.kiwi", profile = "distroless-minimal" }

[images.container-distroless-base]
description = "Container Distroless Base Image"
definition = { type = "kiwi", path = "container-base/container-base.kiwi", profile = "distroless-base" }

[images.container-distroless-debug]
description = "Container Distroless Debug Image"
definition = { type = "kiwi", path = "container-base/container-base.kiwi", profile = "distroless-debug" }

# NOTE:
# sudo dnf install -y kiwi-cli
# sudo kiwi --loglevel 10 \
#     --kiwi-file container-base.kiwi \
#     system build \
#     --description ./container-base \
#     --target-dir <output_dir> \
#     --add-repo='file:///home/username/some/dir/with/private/rpms,rpm-md,azl,1
