.TH PRE\-COMMIT\-CLEAN "1" "February 2025" "" "User Commands"
.SH NAME
.B pre\-commit\-clean
\[en]
Clean out pre-commit files
.SH SYNOPSIS
.B pre\-commit\ clean
.RB [ \-h ]
.RB [ \-\-color\  { auto , always , never }]
.SH OPTIONS
.\" .SS "POSITIONAL\ ARGUMENTS"
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit.
.TP
.BR \-\-color\  { auto , always , never }
Whether to use color in output.
Defaults to
.BR auto .
.SH "SEE\ ALSO"
.BR pre\-commit\-autoupdate (1),
.\" .BR pre\-commit\-clean (1),
.BR pre\-commit\-gc (1),
.BR pre\-commit\-init\-templatedir (1),
.BR pre\-commit\-install (1),
.BR pre\-commit\-install\-hooks (1),
.BR pre\-commit\-migrate\-config (1),
.BR pre\-commit\-run (1),
.BR pre\-commit\-sample\-config (1),
.BR pre\-commit\-try\-repo (1),
.BR pre\-commit\-uninstall (1),
.BR pre\-commit\-validate\-config (1),
.BR pre\-commit\-validate\-manifest (1),
.BR pre\-commit\-help (1)
.P
.BR pre\-commit (1)
