.TH PRE\-COMMIT\-INSTALL "1" "February 2025" "" "User Commands"
.SH NAME
.B pre\-commit\-install
\[en]
Install the pre-commit script
.SH SYNOPSIS
.B pre\-commit\ install
.RB [ \-h ]
.RB [ \-\-color\  { auto , always , never }]
.RB [ \-c\ \fICONFIG ]
.RB [ \-f ]
.RB [ \-\-install\-hooks ]
.RB [ \-t\  { commit\-msg , post\-checkout , post\-commit , post\-merge , post\-rewrite , pre\-commit , pre\-merge\-commit , pre\-push , pre\-rebase , prepare\-commit\-msg }]
.RB [ \-\-allow\-missing\-config ]
.SH OPTIONS
.\" .SS "POSITIONAL\ ARGUMENTS"
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit.
.TP
.BR \-\-color\  { auto , always , never }
Whether to use color in output.
Defaults to
.BR auto .
.TP
.B \-c\fR, \fB\-\-config\ \fICONFIG
Path to alternate config file.
.TP
.B \-f\fR, \fB\-\-overwrite
Overwrite existing hooks / remove migration mode.
.TP
.B \-\-install\-hooks
Whether to install hook environments
for all environments in the config file.
.TP
.BR \-t ,\  \-\-hook\-type\  { commit\-msg , post\-checkout , post\-commit , post\-merge , post\-rewrite , pre\-commit , pre\-merge\-commit , pre\-push , pre\-rebase , prepare\-commit\-msg }
.TP
.B \-\-allow\-missing\-config
Whether to allow a missing
.B pre-commit
configuration file or exit with a failure code.
.SH "SEE\ ALSO"
.BR pre\-commit\-autoupdate (1),
.BR pre\-commit\-clean (1),
.BR pre\-commit\-gc (1),
.BR pre\-commit\-init\-templatedir (1),
.\" .BR pre\-commit\-install (1),
.BR pre\-commit\-install\-hooks (1),
.BR pre\-commit\-migrate\-config (1),
.BR pre\-commit\-run (1),
.BR pre\-commit\-sample\-config (1),
.BR pre\-commit\-try\-repo (1),
.BR pre\-commit\-uninstall (1),
.BR pre\-commit\-validate\-config (1),
.BR pre\-commit\-validate\-manifest (1),
.BR pre\-commit\-help (1)
.P
.BR pre\-commit (1)
