# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG BASE_IMAGE

FROM $BASE_IMAGE

@INCLUDE_MAIN_RUN_INSTRUCTION@

#simple smoke test
RUN ls /usr/bin/cluster-api-provider-kubevirt-manager

# Use uid of nonroot user (65532) because kubernetes expects numeric user when applying pod security policies
USER 65532

ENTRYPOINT ["/usr/bin/cluster-api-provider-kubevirt-manager"]

