.TH SGMLWHICH 1
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.SH NAME
sgmlwhich \- prints location of main sgml configuration file
.SH SYNOPSIS
.B sgmlwhich

.SH "DESCRIPTION"
Simple script which prints location of main sgml configuration file.
It is provided for consistency with non-LSB platforms.

.SH OPTIONS
Script doesn't accept any options.

.SH "SEE ALSO"
.\" Always quote multiple words for .SH
.BR sgml.conf (5)

.SH AUTHOR
Eric Bischoff <eric@caldera.de>
