# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG BASE_IMAGE

FROM $BASE_IMAGE

@INCLUDE_MAIN_RUN_INSTRUCTION@

RUN set -eux && \
    valkey-cli --version && \
    valkey-server --version && \
    mkdir /data && \
    chown valkey:valkey /data

VOLUME /data
WORKDIR /data

COPY valkey-docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/valkey-docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/valkey-docker-entrypoint.sh"]

EXPOSE 6379
CMD ["valkey-server"]