## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 4;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

# Generated by rust2rpm 27
# * tests depend on files that are not included in published crates
%bcond check 0
%global debug_package %{nil}

%global crate picky-asn1-x509

Name:           rust-picky-asn1-x509_0.12
Version:        0.12.0
Release:        %autorelease
Summary:        ASN1 types defined by X.509 related RFCs

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/picky-asn1-x509
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Provides ASN1 types defined by X.509 related RFCs.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ctl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ctl-devel %{_description}

This package contains library source intended for building other packages which
use the "ctl" feature of the "%{crate}" crate.

%files       -n %{name}+ctl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+legacy-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+legacy-devel %{_description}

This package contains library source intended for building other packages which
use the "legacy" feature of the "%{crate}" crate.

%files       -n %{name}+legacy-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+num-bigint-dig-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+num-bigint-dig-devel %{_description}

This package contains library source intended for building other packages which
use the "num-bigint-dig" feature of the "%{crate}" crate.

%files       -n %{name}+num-bigint-dig-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pkcs12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pkcs12-devel %{_description}

This package contains library source intended for building other packages which
use the "pkcs12" feature of the "%{crate}" crate.

%files       -n %{name}+pkcs12-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pkcs7-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pkcs7-devel %{_description}

This package contains library source intended for building other packages which
use the "pkcs7" feature of the "%{crate}" crate.

%files       -n %{name}+pkcs7-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+widestring-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+widestring-devel %{_description}

This package contains library source intended for building other packages which
use the "widestring" feature of the "%{crate}" crate.

%files       -n %{name}+widestring-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+zeroize-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+zeroize-devel %{_description}

This package contains library source intended for building other packages which
use the "zeroize" feature of the "%{crate}" crate.

%files       -n %{name}+zeroize-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
## START: Generated by rpmautospec
* Wed Apr 22 2026 azldev <azurelinux@microsoft.com> - 0.12.0-4
- Latest state for rust-picky-asn1-x509_0.12

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.12.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Sun Jan 19 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.12.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Wed Jan 15 2025 Fabio Valentini <decathorpe@gmail.com> - 0.12.0-1
- Initial import (picky-asn1-x509 0.12 compat package)
## END: Generated by rpmautospec
