#!/bin/bash

# Use a custom termcap for the Mariner installer in an ISO environment
# for a high contrast cursor. This is based on the "linux" termcap.
export TERMINFO=/usr/lib/mariner/terminfo
export TERM=mariner-installer

# Mounting the ISO root for the installer.
ISO_ROOT=/mnt/cdrom
mkdir -p $ISO_ROOT
LABEL=CDROM

if grep -qs $ISO_ROOT /proc/mounts; then
    echo ISO root already mounted
else
    echo Attempt to mount the ISO root
    # It is possible that the partition isn't ready to be mounted when this script
    # is first run. So use a retry loop.
    RETRY=0
    LIMIT=5
    SLEEPSECONDS=2
    while [ $RETRY -lt $LIMIT ]
    do
        mount -L $LABEL -o ro $ISO_ROOT && break
        echo Mount failed. Retrying...
        ((RETRY++))
        sleep $SLEEPSECONDS
    done
fi

CONFIG_ROOT=$ISO_ROOT/config
UNATTENDED_CONFIG_FILE=$CONFIG_ROOT/unattended_config.json
TEMPDIR=$(mktemp -d)

# kickstart param is used to specify an unattended config file that is not part of an .iso image
#
# note:
# - existing unattended config file is always preferred to kickstart param
# - only 'ks=value' is recognized (=> 'ks=value' cannot contain space)
#
GRUB_PARAM=$(cat /proc/cmdline)
if [[ ! -f "$UNATTENDED_CONFIG_FILE" && \
      $GRUB_PARAM == *"ks="* ]]; then
    # value of kickstart param is 1st item in the array
    GRUB_PARAMS_FROM_KICKSTART=${GRUB_PARAM#*ks=}
    read -a PARAM <<< "$GRUB_PARAMS_FROM_KICKSTART"
    KICKSTART_PARAM=${PARAM[0]}

    echo "unattended config file: $KICKSTART_PARAM"

    # download unattended config file if necessary
    if [[ $KICKSTART_PARAM == "http://"* || \
        $KICKSTART_PARAM == "https://"* ]]; then
        UNATTENDED_CONFIG_FILE=$TEMPDIR/unattended_config.json
        curl $KICKSTART_PARAM -o $UNATTENDED_CONFIG_FILE
    fi
fi

if [[ ! -f "$UNATTENDED_CONFIG_FILE" ]]; then
    # Restrict speakup use to attended installs
    # FIXME(thcrain-msft)
    # This is a loop of silence to keep the default audio device alive
    # This is a temporary workaround that is needed for VirtualBox,
    # which is currently the most convenient platform to test on which
    # has sound driver support. It creates a bit of hiss.
    speaker-test -l0 -t wav -w ../../../../root/silence.wav -r 22050 >/dev/null 2>&1 &

    # Set better defaults for speakup punctuation level/speed
    echo 2 > /sys/accessibility/speakup/punc_level
    echo 2 > /sys/accessibility/speakup/reading_punc
    echo 2 > /sys/accessibility/speakup/soft/rate

    # Ensure the userspace speakup connector is up
    systemctl enable espeakup
    systemctl start espeakup
    fi
fi

cd /installer

# Turn off echoing while the installer runs to stop sensitive data from rendering in the TTY session.
stty -echo

./liveinstaller --base-dir $CONFIG_ROOT --imager /installer/imager --input $UNATTENDED_CONFIG_FILE --template-config $CONFIG_ROOT/attended_config.json \
                --build-dir $PWD --log-file=/installer/log.txt
installerExitCode=$?

rm -rf $TEMPDIR

# Consume any buffered stdin to prevent it from being passed to any future programs,
# as it may contain sensitive data
while read -t 1 -n 10000
do
    echo ""
done

# Turn back on echoing input so the TTY session is usable for the user.
stty echo

if [ $installerExitCode -eq 0 ]; then
    reboot
else
    /bin/bash
fi
