# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

ARG BASE_IMAGE

FROM $BASE_IMAGE

@INCLUDE_MAIN_RUN_INSTRUCTION@

# Setup permissions and capabilities for non-root VMIs. KubeVirt sets
# XDG_* directories to /var/run.
RUN  cd /var && rm -rf run && ln -s ../run . \
   && chown qemu:qemu /var/run \
   && setcap 'cap_net_bind_service=+ep' /usr/bin/virt-launcher \
   && setcap 'cap_net_bind_service=+ep' /usr/bin/virt-launcher-monitor \
   && chmod 0755 /etc/libvirt

RUN cp /usr/share/kube-virt/virt-launcher/qemu.conf /etc/libvirt/
RUN cp /usr/share/kube-virt/virt-launcher/virtqemud.conf /etc/libvirt/

#simple smoke test
RUN ls /usr/bin/virt-launcher

COPY virt-launcher-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/virt-launcher-entrypoint.sh"]