.TH HATCHLING\-DEP "1" "October 2022" "" "User Commands"
.SH NAME
.B hatchling\ dep
.SH SYNOPSIS
.B hatchling\ dep
.RB [ \-h ]
.RB { synced }\ ...
.SH OPTIONS
.SS "COMMANDS"
.TP
.B synced
See
.BR hatchling\-dep\-synced (1).
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit
.SH "SEE\ ALSO"
.BR hatchling\-dep\-synced (1)
.P
.BR hatchling\-build (1),
.BR hatchling\-metadata (1),
.BR hatchling\-version (1)
.P
.BR hatchling (1)
