.TH HATCHLING\-BUILD "1" "October 2022" "" "User Commands"
.SH NAME
.B hatchling\ build
.SH SYNOPSIS
.B hatchling\ build
.RB [ \-h ]
.RB [ \-d ]
.RB [ \-t ]
.RB [ \-\-hooks\-only ]
.RB [ \-\-no\-hooks ]
.RB [ \-c ]
.RB [ \-\-clean\-hooks\-after ]
.RB [ \-\-clean\-only ]
.SH OPTIONS
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit
.TP
.B \-d\fR,\ \fB\-\-directory
The directory in which to build artifacts
.TP
.B \-t\fR,\ \fB\-\-targets
Comma-separated list of targets to build, overriding project defaults
.TP
.B \-\-hooks\-only
.TP
.B \-\-no\-hooks
.TP
.B \-c\fR,\ \fB\-\-clean
.TP
.B \-\-clean\-hooks\-after
.TP
.B \-\-clean\-only
.SH "SEE\ ALSO"
.BR hatchling\-dep (1),
.BR hatchling\-metadata (1),
.BR hatchling\-version (1)
.P
.BR hatchling (1)
