.TH HATCHLING "1" "October 2022" "" "User Commands"
.SH NAME
.B hatchling
\(en the build backend used by Hatch
.SH SYNOPSIS
.B hatchling
.RB [ \-h ]
.RB { build , dep , metadata , version }\ ...
.SH DESCRIPTION
This is the extensible, standards compliant build backend used by Hatch.
.SH OPTIONS
.SS "COMMANDS"
.TP
.B build
See
.BR hatchling\-build (1).
.TP
.B dep
See
.BR hatchling\-dep (1).
.TP
.B metadata
See
.BR hatchling\-metadata (1).
.TP
.B version
See
.BR hatchling\-version (1).
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit
.SH "SEE\ ALSO"
.BR hatchling\-build (1),
.BR hatchling\-dep (1),
.BR hatchling\-metadata (1),
.BR hatchling\-version (1)
.P
.BR hatch (1)
