.TH HATCHLING\-DEP\-SYNCED "1" "October 2022" "" "User Commands"
.SH NAME
.B hatchling\ dep\ synced
.SH SYNOPSIS
.B hatchling\ dep\ synced
.RB [ \-h ]
.RB [ \-p ]
.I dependencies
.RI [ dependencies \ ...]
.SH OPTIONS
.SS "POSITIONAL\ ARGUMENTS"
.TP
.I dependencies
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit
.TP
.B \-p\fR,\ \fB\-\-python
.SH "SEE\ ALSO"
.BR hatchling\-dep (1),
.BR hatchling (1)
