.TH HATCHLING\-VERSION "1" "October 2022" "" "User Commands"
.SH NAME
.B hatchling\ version
.SH SYNOPSIS
.B hatchling\ version
.RB [ \-h ]
.SH OPTIONS
.\" .SS "POSITIONAL\ ARGUMENTS"
.SS "OPTIONAL\ ARGUMENTS"
.TP
.B \-h\fR,\ \fB\-\-help
Show a help message and exit
.SH "SEE\ ALSO"
.BR hatchling\-build (1),
.BR hatchling\-dep (1),
.BR hatchling\-metadata (1)
.P
.BR hatchling (1)
