#!/bin/bash
# Simple deployment script using Azure Portal upload

echo "🚀 Deploying radarfunc via Portal Upload"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Open this URL in your browser:"
echo "   https://radarfunc-eka5fmceg4b5fub0.scm.canadacentral-01.azurewebsites.net"
echo ""
echo "2. You'll see the Kudu homepage"
echo ""
echo "3. Click on 'Tools' in the top menu bar"
echo ""
echo "4. Select 'Zip Push Deploy' from the dropdown"
echo ""
echo "5. You'll see a drag-and-drop zone for '/site/wwwroot'"
echo ""
echo "6. Drag this file into the drop zone:"
echo "   $(pwd)/radarfunc-auth.zip"
echo ""
echo "7. Wait for the green checkmark (deployment complete)"
echo ""
echo "8. The function will automatically restart"
echo ""
echo "Alternative: Use file browser to upload manually"
echo "If Zip Push Deploy doesn't work:"
echo "- Click 'Debug console' → 'CMD' in Kudu"
echo "- Navigate to site/wwwroot"
echo "- Delete all existing files"
echo "- Upload radarfunc-auth.zip"
echo "- Unzip it using: unzip radarfunc-auth.zip"
echo ""
echo "📍 Kudu URL: https://radarfunc-eka5fmceg4b5fub0.scm.canadacentral-01.azurewebsites.net"
echo "📦 ZIP file: $(pwd)/radarfunc-auth.zip"
echo ""
