extraction:
  cpp:
    prepare:
      packages:
      - autoconf-archive
      - libssl-dev
    after_prepare:
    - cd "$LGTM_WORKSPACE"
    - mkdir installdir
    - git clone https://github.com/stefanberger/libtpms.git
    - cd libtpms
    - ./bootstrap.sh
    - ./configure --prefix="$LGTM_WORKSPACE/installdir/usr"
    - make install
    - export PKG_CONFIG_PATH="$LGTM_WORKSPACE/installdir/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
    - export LD_LIBRARY_PATH="$LGTM_WORKSPACE/installdir/usr/lib:$LD_LIBRARY_PATH"
    - export C_INCLUDE_PATH="$LGTM_WORKSPACE/installdir/usr/include/";
