.TH XML-XPARSE 1 "11 April 2013" "xml-commons-resolver" "User commands"

.SH NAME
xml-xparse - A simple command-line XML parsing application

.SH SYNOPSIS

.B xml-xparse
[options] document.xml

.SH DESCRIPTION

\fBxml-xparse\fP is a simple command-line XML Parser. It's just a little 
wrapper around the JAXP Parser with support for catalogs.

The process ends with error-level 1, if there were errors.

.SH OPTIONS

Command-line options are described below.

.PP
.B -c
catalogfile
.RS 4
Load a particular catalog file
.RE
.PP
.B -w
.RS 4
Perform a well-formed parse, not a validating parse
.RE
.PP
.B -v
(default)
.RS 4
Perform a validating parse
.RE
.PP
.B -n
.RS 4
Perform a namespace-ignorant parse
.RE
.PP
.B -N
(default)
.RS 4
Perform a namespace-aware parse
.RE
.PP
.B -d
integer
.RS 4
Set the debug level. Warnings are shown if the debug level is > 2
.RE
.PP
.B -E
integer
.RS 4
Set the maximum number of errors to display
.RE

