[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/NunoDasNeves/vfio?branch=nudasnev/mshv-ioctls-v0.3.0"]
git = "https://github.com/NunoDasNeves/vfio"
branch = "nudasnev/mshv-ioctls-v0.3.0"
replace-with = "vendored-sources"

[source."git+https://github.com/firecracker-microvm/micro-http?branch=main"]
git = "https://github.com/firecracker-microvm/micro-http"
branch = "main"
replace-with = "vendored-sources"

[source."git+https://github.com/rust-vmm/acpi_tables?branch=main"]
git = "https://github.com/rust-vmm/acpi_tables"
branch = "main"
replace-with = "vendored-sources"

[source."git+https://github.com/rust-vmm/mshv?tag=v0.3.0"]
git = "https://github.com/rust-vmm/mshv"
tag = "v0.3.0"
replace-with = "vendored-sources"

[source."git+https://github.com/rust-vmm/vfio-user?branch=main"]
git = "https://github.com/rust-vmm/vfio-user"
branch = "main"
replace-with = "vendored-sources"

[source."git+https://github.com/rust-vmm/vm-fdt?branch=main"]
git = "https://github.com/rust-vmm/vm-fdt"
branch = "main"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
