.TH DATEPARSER\-DOWNLOAD "1" "March 2023" "" "User Commands"
.SH NAME
.B dateparser\-download
\(en dateparser download manager
.SH SYNOPSIS
.B dateparser\-download
.RB [ \-h ]
.RB [ \-\-fasttext\ \fIFASTTEXT ]
.RB [ \-\-clear ]
.SH OPTIONS
.TP
.BR \-h ,\  \-\-help
Show a help message and exit
.TP
.B \-\-fasttext\ \fIFASTTEXT
Download a fasttext language detection model.
Supported models are
.RB \(lq small \(rq
and
.RB \(lq large \(rq
.TP
.B \-\-clear ,\  \-\-clear\-cache
Clear all cached models
