%global _dracut_conf_d  %{_prefix}/lib/dracut/dracut.conf.d

# gsp_*.bin: ELF 64-bit LSB executable, UCB RISC-V
%global _binaries_in_noarch_packages_terminate_build 0
%global __strip /bin/true

Name:           nvidia-kmod-common
Version:        610.57.04
Release:        1%{?dist}
Summary:        Common file for NVIDIA's proprietary driver kernel modules
License:        NVIDIA License
URL:            http://www.nvidia.com/object/unix.html
Vendor:         NVIDIA
Packager:       NVIDIA

BuildArch:      noarch

# AZL: upstream Source0 is %{name}-%{version}.tar.xz, produced by NVIDIA's own
# nvidia-generate-tarballs.sh from the .run installer below (only the
# firmware/ tree is used). We vendor the installer directly and reproduce that
# extraction in %prep instead.
Source0:        NVIDIA-Linux-x86_64-%{version}.run
Source1:        nvidia-boot-update
Source20:       nvidia.conf
Source21:       99-nvidia.conf
Source22:       60-nvidia.rules
Source23:       nvidia.cfg

# UDev rule location (_udevrulesdir) and systemd macros:
BuildRequires:  systemd-rpm-macros

Requires:       nvidia-modprobe = %{version}
Requires:       nvidia-kmod = %{version}
Provides:       nvidia-kmod-common = %{version}

%description
This package provides the common files required by all NVIDIA kernel module
package variants.
 
%prep
sh %{SOURCE0} --extract-only --target %{name}-%{version}
%setup -q -T -D -n %{name}-%{version}

%install
# Load nvidia-uvm, blacklist nouveau/nova:
install -p -m 0644 -D %{SOURCE20} %{buildroot}%{_modprobedir}/nvidia.conf

# Avoid Nvidia modules getting in the initrd:
install -p -m 0644 -D %{SOURCE21} %{buildroot}%{_dracut_conf_d}/99-nvidia.conf

# UDev rules:
# https://github.com/NVIDIA/nvidia-modprobe/blob/master/modprobe-utils/nvidia-modprobe-utils.h#L33-L46
# https://github.com/negativo17/nvidia-kmod-common/issues/11
# https://github.com/negativo17/nvidia-driver/issues/27
install -p -m 644 -D %{SOURCE22} %{buildroot}%{_udevrulesdir}/60-nvidia.rules

# Firmware files:
mkdir -p %{buildroot}%{_prefix}/lib/firmware/nvidia/%{version}/
install -p -m 644 firmware/* %{buildroot}%{_prefix}/lib/firmware/nvidia/%{version}

%if 0%{?azl3} >= 1

# Disable nouveau/nova and kernel lockdown at boot:
install -p -m 0644 -D %{SOURCE23} %{buildroot}%{_sysconfdir}/default/grub.d/nvidia.cfg

%post
if [ -x /usr/sbin/grub2-mkconfig ] && grep -q -e "automatically generated by grub2-mkconfig" /boot/grub2/grub.cfg; then
    /usr/sbin/grub2-mkconfig > /boot/grub2/grub.cfg || :
fi

%postun
if [ -x /usr/sbin/grub2-mkconfig ] && grep -q -e "automatically generated by grub2-mkconfig" /boot/grub2/grub.cfg; then
    /usr/sbin/grub2-mkconfig > /boot/grub2/grub.cfg || :
fi

%elif 0%{?azl4} >= 1

# Script for post/preun tasks
install -p -m 0755 -D %{SOURCE1} %{buildroot}%{_sbindir}/nvidia-boot-update

%post
%{_sbindir}/nvidia-boot-update post

%preun
if [ "$1" -eq "0" ]; then
  %{_sbindir}/nvidia-boot-update preun
fi ||:

%endif

%files
%{_dracut_conf_d}/99-nvidia.conf
%{_modprobedir}/nvidia.conf
%dir %{_prefix}/lib/firmware
%{_prefix}/lib/firmware/nvidia
%{_udevrulesdir}/60-nvidia.rules
%if 0%{?azl3} >= 1
%config %{_sysconfdir}/default/grub.d/nvidia.cfg
%elif 0%{?azl4} >= 1
# AZL: upstream %files lists %{_bindir}/nvidia-boot-update, but %install
# installs it to %{_sbindir}; fixed to match the actual install path.
%{_sbindir}/nvidia-boot-update
%endif

%changelog
