## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 2;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate gix-validate

Name:           rust-gix-validate
Version:        0.10.1
Release:        %autorelease
Summary:        Validation functions for various kinds of names in git

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/gix-validate
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Validation functions for various kinds of names in git.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
## START: Generated by rpmautospec
* Wed Apr 22 2026 azldev <azurelinux@microsoft.com> - 0.10.1-2
- Latest state for rust-gix-validate

* Mon Dec 22 2025 blinxen <h-k-81@hotmail.com> - 0.10.1-1
- Update to version 0.10.1

* Sun Aug 10 2025 blinxen <h-k-81@hotmail.com> - 0.10.0-1
- Update to version 0.10.0 (rhbz#2357417)

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Wed Jan 22 2025 blinxen <h-k-81@hotmail.com> - 0.9.3-1
- Update to version 0.9.3 (rhbz#2338747)

* Sun Jan 19 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.9.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Thu Nov 28 2024 Fabio Valentini <decathorpe@gmail.com> - 0.9.2-1
- Update to version 0.9.2; Fixes RHBZ#2328537

* Tue Nov 12 2024 Fabio Valentini <decathorpe@gmail.com> - 0.9.1-1
- Update to version 0.9.1; Fixes RHBZ#2321190

* Tue Sep 10 2024 blinxen <h-k-81@hotmail.com> - 0.9.0-1
- Update to version 0.9.0 (rhbz#2307407)

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.5-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Sun Jun 23 2024 blinxen <h-k-81@hotmail.com> - 0.8.5-1
- Update to version 0.8.5 (rhbz#2282462)

* Fri Apr 05 2024 blinxen <h-k-81@hotmail.com> - 0.8.4-1
- Update to version 0.8.4 (rhbz#2269605)

* Tue Jan 30 2024 Fabio Valentini <decathorpe@gmail.com> - 0.8.3-1
- Update to version 0.8.3; Fixes RHBZ#2253243

* Fri Jan 26 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.8.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Thu Aug 10 2023 blinxen <h-k-81@hotmail.com> - 0.8.0-1
- Update to version 0.8.0 (rhbz#2229633)

* Thu Jul 27 2023 Fabio Valentini <decathorpe@gmail.com> - 0.7.7-1
- Update to version 0.7.7; Fixes RHBZ#2224746

* Fri Jul 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 0.7.6-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Fri Jun 23 2023 Fabio Valentini <decathorpe@gmail.com> - 0.7.6-1
- Update to version 0.7.6; Fixes RHBZ#2216742

* Tue Jun 06 2023 blinxen <h-k-81@hotmail.com> - 0.7.5-1
- Initial package
## END: Generated by rpmautospec
