.TH filebench 1  "Sep 1, 2011" "revision 01" "USER COMMANDS"
.SH NAME
filebench \- interprets WML script and generates appropriate filesystem workload
.SH SYNOPSIS
.B filebench [-f <filename>] [-h]
.SH DESCRIPTION
.B Filebench
is a file system and storage benchmark that allows to generate a large variety of workloads. Unlike typical benchmarks it is very flexible and allows to minutely specify (any) applications' behaviour using extensive Workload Model Language (WML). Filebench uses loadable workload personalities to allow easy emulation of complex applications (e.g., mail, web, file, and database servers). Filebench is quick to set up and easy to use compared to deploying real applications. It is also a handy tool for micro-benchmarking.
.PP
.B Filebench
includes many features to facilitate file system benchmarking:
.IP \[bu] 2
Multiple workload types support via loadable personalities
.IP \[bu]
Ships with more than 40 pre-defined personalities, including the one that describe mail, web, file, and database servers behaviour
.IP \[bu]
Easy to add new personalities using reach Workload Model Language (WML)
.IP \[bu]
Multi-process and multi-thread workload support
.IP \[bu]
Configurable directory hierarchies with depth, width, and file sizes set to given statistical distributions
.IP \[bu]
Support of asynchronous I/O and process synchronization primitives
.IP \[bu]
Integrated statistics for throughput, latency, and CPU cycle counts per system call 

.SH OPTIONS
.TP
\-f <filename>
use specified file as an input instead of stdin
.TP
\-h
Display verbose help
.SH EXAMPLES
.TP
Run filebench interactively:
.TP
.B $ filebench
Start filebench interactive shell, filebench prompt will appear after that.
.TP
.B filebench> load fileserver
Load fileserver personality using load command.
.TP
.B filebench> set $dir=/mnt
After personality is loaded, tunables of the workload personality can be set. Here we change the benchmark directory to /mnt where the file system we want to benchmark is presumably mounted.
.TP
.B filebench> run 60
Start workload for 60 seconds. After 60 seconds of the run the statistics is printed and Filebench exits.
.TP
Run filebench non-interactively:
.TP
.B filebench -f /usr/share/filebench/workloads/fileserver.f
Run filebench non-interactively, however, you need to add 'run <time>' to the end of the workload personality file before calling filebench.
.PP
.SH EXIT STATUS
.TP
0 if OK,
.TP
1 if workload file is not found.
.SH REPORTING BUGS
http://sourceforge.net/tracker/?group_id=133644&atid=727883

