.\" Process this file with
.\" groff -man -Tascii ipmaddr.8
.\"
.TH IPMADDR 8 "SEPTEMBER 2009" "" ""
.\"
.\" Man page written by Jiri Popelka <jpopelka AT redhat DOT com>
.\"
.SH NAME
.B ipmaddr
\- adds, deletes, and displays multicast addresses
 
.SH SYNOPSIS
.B /usr/sbin/ipmaddr
.RB [< operation >]
.RB [< args >]

.SH NOTE
.P
This program is obsolete. For replacement check \fBip maddr\fR.

.SH DESCRIPTION
The \fBipmaddr\fR command can perform one of the following operations:

.B add
\- add a multicast address

.B del
\- delete a multicast address

.B show
\- list multicast addresses

.SH SEE ALSO
.BR ip (8).
