.\" -*- nroff -*-
.\" Portions of this file are subject to the following copyright.  See
.\" the Net-SNMP COPYING file for more details and other copyrights
.\" that may apply:
.\" /***********************************************************
.\" 	Copyright 1989 by Carnegie Mellon University
.\" 
.\"                       All Rights Reserved
.\" 
.\" Permission to use, copy, modify, and distribute this software and its 
.\" documentation for any purpose and without fee is hereby granted, 
.\" provided that the above copyright notice appear in all copies and that
.\" both that copyright notice and this permission notice appear in 
.\" supporting documentation, and that the name of CMU not be
.\" used in advertising or publicity pertaining to distribution of the
.\" software without specific, written prior permission.  
.\" 
.\" CMU DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING
.\" ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL
.\" CMU BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR
.\" ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
.\" WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
.\" ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
.\" SOFTWARE.
.\" ******************************************************************/
.TH SNMPTRAPD 8 "27 Apr 2014" V5.8 "Net-SNMP"
.\"O .SH NAME
.SH 名前
.\"O snmptrapd - Receive and log SNMP trap messages.
snmptrapd - SNMP trap メッセージの受信と記録
.\"O .SH SYNOPSIS
.SH 書式
.BR snmptrapd " [OPTIONS] [LISTENING ADDRESSES]"
.\"O .SH DESCRIPTION
.SH 説明
.B snmptrapd
.\"O is an SNMP application that receives and logs SNMP TRAP and INFORM
.\"O messages.
は SNMP TRAP や INFORM メッセージを受信し記録する SNMP アプリケーションである。
.PP
.\"O Note: the default is to listen on UDP port 162 on all IPv4 interfaces.
注意: デフォルトはすべての IPv4 インターフェースの UDP ポート 162 上で動作する。
.\"O Since 162 is a privileged port,
162 は特権ポートなので、
.B snmptrapd
.\"O must typically be run as root.
は典型的に root として実行しなくてはならない。
.\"O .SH OPTIONS
.SH オプション
.TP 8
.B \-a
.\"O Ignore authenticationFailure traps.
authenticationFailure trap を無視する。
.TP
.B \-A
.\"O Append to the log file rather than truncating it.
切り捨てずにログファイルへ追記する。

.\"O Note that this needs to come \fIbefore\fP any \-Lf options
.\"O that it should apply to.
このオプションはこれが適用される \-Lf オプションの \fI前に\fP 指定する必要がある点に注意。
.TP
.BI "\-c" " FILE"
.\"O Read 
.I FILE
.\"O as a configuration file
を設定ファイルとして読み込む。
.\"O (or a comma-separated list of configuration files).
(あるいはコンマで区切られた設定ファイルのリスト)
.TP
.B \-C
.\"O Do not read any configuration files except the one optionally specified by the 
.\"O .B \-c 
.\"O option.
.B \-c
オプションで指定したものを除いて、設定ファイルを読み込まない。
.TP
.B \-d
.\"O Dump (in hexadecimal) the sent and received SNMP packets.
送受信した SNMP パケットを (16 進数で) ダンプする。
.TP
.BI \-D[TOKEN[,...]]
.\"O Turn on debugging output for the given
.\"O .IR "TOKEN" "(s)."
.IR "TOKEN" "(s)"
で与えられたデバッグ出力を有効にする。
.\"O Try
.\"O .IR ALL
.\"O for extremely verbose output.
極めて冗長な出力を得るには
.IR ALL
を指定する。
.TP
.B \-f
.\"O Do not fork() from the calling shell.
呼び出し shell から fork() しない。
.TP
.BI \-F " FORMAT"
.\"O When logging to standard output, use the format in the string
.\"O .IR FORMAT .
標準出力へ記録する時、
.IR FORMAT
文字で指定されたフォーマットを使う。
.\"O See the section
.\"O .B FORMAT SPECIFICATIONS
.\"O below for more details.
詳細は以下の
.B フォーマットの仕様
セクションを参照。
.TP
.B \-h, \-\-help
.\"O Display a brief usage message and then exit.
簡単な使用法を表示して終了する。
.TP
.B \-H
.\"O Display a list of configuration file directives understood by the
.\"O trap daemon and then exit.
trap デーモンが理解する設定ファイルのディレクティブのリストを表示して終了する。
.TP
.B \-I \fI[\-]INITLIST
.\"O Specifies which modules should (or should not) be initialized
.\"O when snmptrapd starts up.  If the comma-separated
snmptrapd が動き始める時に、どのモジュールを初期化すべきか (あるいはすべきではないか) を指定する。
.\"O .I INITLIST
.\"O is preceded
.\"O with a '\-', it is the list of modules that should \fInot\fR be started.
コンマ区切りの
.I INITLIST
の前に '\-' がついた場合は、開始すべき \fIではない\fR モジュールのリストである。
.\"O Otherwise this is the list of the \fIonly\fR modules that should be started.
それ以外の場合は、開始すべき \fI唯一の\fR モジュールリストである。

.\"O To get a list of compiled modules, run snmptrapd with the arguments
.\"O .I "\-Dmib_init \-H"
.\"O (assuming debugging support has been compiled in).
コンパイルされたモジュールのリストを得るには、
.I "\-Dmib_init \-H"
オプションとともに snmptrapd を実行する。
(デバッグサポートをコンパイル時に有効にする必要がある)
.TP
.B \-L[efos]
.\"O Specify where logging output should be directed (standard error or output,
.\"O to a file or via syslog).  See LOGGING OPTIONS in \fIsnmpcmd(1)\fR for details.
ログの出力がどこへ向けられるべきかを指定する。(標準エラーあるいは標準出力、ファイルへ、ないし、syslog経由)
詳細は \FIsnmpcmd(1)\FR 内のログオプションを参照。
.TP
.BR \-m " \fIMIBLIST"
.\"O Specifies a colon separated list of MIB modules to load for this
.\"O application.  This overrides the environment variable MIBS.
.\"O See \fIsnmpcmd(1)\fR for details.
このアプリケーションで読み込む MIB モジュールのリストをコンマ区切りで指定する。
これは環境変数 MIBS を上書きする。
詳細は \fIsnmpcmd(1)\fR を参照。
.TP
.BR \-M " \fIDIRLIST"
.\"O Specifies a colon separated list of directories to search for MIBs.
.\"O This overrides the environment variable MIBDIRS.
.\"O See \fIsnmpcmd(1)\fR for details.
MIB を探すためのディレクトリリストをコンマ区切りで指定する。
これは環境変数　MIBDIRS を上書きする。
詳細は \fIsnmpcmd(1)\fR を参照。
.TP
.BR \-n
.\"O Do not attempt to translate source addresses of incoming packets into
.\"O hostnames.
受信パケットのソースアドレスからホスト名への変換を試みない。
.TP
.BI \-p " FILE"
.\"O Save the process ID of the trap daemon in
.\"O .IR FILE "."
trap デーモンのプロセス ID を
.IR FILE
へ保存する。
.TP
.BI \-O " [abeEfnqQsStTuUvxX]"
.\"O Specifies how MIB objects and other output should be displayed.
MIB オブジェクトやその他の出力がどのように表示されるべきかを指定する。
.\"O See the section
.\"O .B OUTPUT OPTIONS
.\"O in the
.\"O .I snmpcmd(1)
.\"O manual page for details.
詳細は
.I snmpcmd(1)
マニュアルページの
.B 出力オプション
セクションを参照。
.TP
.BI \-t
.\"O Do not log traps to syslog.  This disables logging to syslog.  This is
.\"O useful if you want the snmptrapd application to
.\"O .B only
.\"O run traphandle hooks and not to log any traps to any location.
trap を syslog へ記録しない。 これは syslog への記録を無効にする。
これは、snmptrapd アプリケーションに traphandle フック
.B だけ
を実行させ、 trap を任意の場所へ記録したくない場合に有用である。
.TP
.B \-v, \-\-version
.\"O Print version information for the trap daemon and then exit.
trap デーモンのバージョン情報を表示し終了する。
.TP
.B \-x \fIADDRESS
.\"O Connect to the AgentX master agent on the specified address,
.\"O rather than the default "/var/agentx/master".
.\"O See \fIsnmpd(8)\fR for details of the format of such addresses.
デフォルトの "/var/agentx/master" ではなく、指定したアドレス上の AgentX マスターエージェントへ接続する。
アドレスフォーマットの詳細は \fIsnmpd(8)\fR を参照。
.TP
.B \-X
AgentX マスターエージェントへ接続しない。
.TP
.BI \-\- "name"="value"
.\"O Allows one to specify any token ("name") supported in the
.\"O .I snmptrapd.conf
.\"O file and sets its value to "value". Overrides the corresponding token in the
.\"O .I snmptrapd.conf
.\"O file. See
.\"O .I snmptrapd.conf(5)
.\"O for the full list of tokens.
.I snmptrapd.conf
ファイルでサポートされるトークン ("name") を指定することを許可し、その値を "value" に設定する。
.I snmptrapd.conf
内の対応するトークンを上書きする。
トークンの完全なリストは
.I snmptrapd.conf(5)
を参照。
.\"O .SH FORMAT SPECIFICATIONS
.SH フォーマットの仕様
.PP
.B snmptrapd
.\"O interprets format strings similarly to
.\"O .IR printf(3) .
は
.IR printf(3)
と同様にフォーマット文字を解釈する。
.\"O It understands the following formatting sequences:
次のフォーマットシーケンスを理解する:
.RS 4
.TP 4
.B %%
.\"O a literal %
% の文字リテラル
.TP
.B %a
.\"O the contents of the agent\-addr field of the PDU (v1 TRAPs only)
PDU の agent\-addr フィールドの内容 (v1 TRAP のみ)
.TP
.B %A
.\"O the hostname corresponding to the contents of the agent\-addr field of
.\"O the PDU, if available, otherwise the contents of the agent\-addr field
.\"O of the PDU (v1 TRAPs only).
もし利用可能であれば PDU の agent\-addr フィールドの内容に対応するホスト名、なければ
PDU の agent\-addr フィールドの内容 (v1 TRAP のみ)
.TP
.B %b
.\"O PDU transport address (Note: this is not necessarily an IPv4
.\"O address).
PDU トランスポートアドレス (注意: これは必ずしも IPv4 アドレスではない)
.br
.\"O Something like "[UDP: [172.16.10.12]:23456->[10.150.0.8]]"
"[UDP: [172.16.10.12]:23456->[10.150.0.8]]" のような何か
.TP
.B %B
.\"O PDU source hostname if available, otherwise PDU source address (see
.\"O note above)
もし利用可能であれば PDU ソースホスト名、なければ PDU ソースアドレス (上記の注意点参照)
.TP
.B %E
.\"O SNMPv3 context engine id
SNMPv3 コンテキストエンジン ID
.TP
.B %h
.\"O current hour on the local system
ローカルシステム上の現在の時(hour)
.TP
.B %H
.\"O the hour field from the \fCsysUpTime.0\fR varbind
\fCsysUptime.0\fR varbind からの時 (hour) フィールド
.TP
.B %j
.\"O current minute on the local system
ローカルシステム上の現在の分
.TP
.B %J
.\"O the minute field from the \fCsysUpTime.0\fR varbind
\fCsysUpTime.0\fR varbind からの分フィールド
.TP
.B %k
.\"O current second on the local system
ローカルシステム上の現在の秒
.TP
.B %K
.\"O the seconds field from the \fCsysUpTime.0\fR varbind
\fCsysUpTime.0\fR varbind からの秒フィールド
.TP
.B %l
.\"O current day of month on the local system
ローカルシステム上の現在の月
.TP
.B %L
.\"O the day of month field from the \fCsysUpTime.0\fR varbind
\fCsysUpTime.0\fR varbind からの月フィールド
.TP
.B %m
.\"O current (numeric) month on the local system
ローカルシステム上の現在の月 (数値)
.TP
.B %M
.\"O the numeric month field from the \fCsysUpTime.0\fR varbind
\fCsysUpTime.0\fR varbind からの月 (数値) フィールド
.TP
.B %N
.\"O enterprise string
エンタープライズ文字列
.TP
.B %P
.\"O security information from the PDU (community name for v1/v2c,
.\"O user and context for v3)
PDU からのセキュリティ情報 (v1/v2c ではコミュニティ名、v3ではユーザーとコンテキスト)
.TP
.B %q
.\"O trap sub-type (numeric, in decimal)
trap サブタイプ (10進数)
.TP
.B %s
.\"O SNMP version number (0: v1, 1: v2c, 2: v3)
SNMP バージョン番号 (0: v1, 1: v2c, 2: v3)
.TP
.B %S
.\"O SNMPv3 security model version number
SNMPv3 セキュリティモデルバージョン番号
.TP
.B %t
.\"O decimal number of seconds since the operating system epoch (as
.\"O returned by
.\"O .IR time(2) )
(
.IR time(2)
によって返される)
10進数のオペレーティングシステムの開始時刻 (エポック)
.TP
.B %T
.\"O the value of the \fCsysUpTime.0\fR varbind in seconds
\fCsysUpTime.0\fR varbind の値を秒で
.TP
.B %u
.\"O SNMPv3 security name, or v1/v2c community name
SNMPv3 セキュリティ名あるいは v1/v2c のコミュニティ名
.TP
.B %v
.\"O list of variable-bindings from the notification payload.
通知ペイロードから variable-bindings のリスト。
.\"O These will be separated by a tab, 
.\"O or by a comma and a blank if the alternate form is requested
.\"O See also %V
代替フォームが要求された場合、これらはタブあるいはコンマや空白によって区切られる。
%V も参照。
.TP
.B %V
.\"O specifies the variable-bindings separator. This takes a sequence of
.\"O characters, up to the next % (to embed a % in the string, use \\%)
variable-bindings セパレーターを指定する。
これは次の % まで (文字列に % を埋め込みたい場合は、\\% を使う) 文字のシーケンスを取る。
.TP
.B %w
.\"O trap type (numeric, in decimal)
trap タイプ (10進数)
.TP
.B %W
.\"O trap description
trap の説明
.TP
.B %y
.\"O current year on the local system
ローカルシステム上の現在の年
.TP
.B %Y
.\"O the year field from the \fCsysUpTime.0\fR varbind
\fCsysUpTime.0\fR varbind からの年フィールド
.RE
.PP
.\"O In addition to these values, an optional field
これらの値に加えて、
.\"O width and precision may also be specified , just as in 
.\"O .IR printf(3) ,
.\"O and a flag value. The following flags are supported:
.IR printf(3)
のように幅や精度、 フラグを指定することもできる。 次のフラグがサポートされている:
.RS 4 
.TP 4
.B \-
.\"O left justify
左揃え
.TP
.B 0
.\"O use leading zeros
先行ゼロを使用
.TP
.B #
.\"O use alternate form
代替フォームを使用
.RE
.PP
.\"O The "use alternate form" flag changes the behavior of various format
.\"O string sequences:
"代替フォームを使用" フラグは様々な文字列シーケンスフォーマットの挙動を変更する:
.IP
.\"O Time information will be displayed based on GMT (rather than the local timezone)
時間情報は (ローカルタイムゾーンではなく) GMT ベースで表示される
.IP
.\"O The variable-bindings will be a comma-separated list (rather than a tab-separated one)
variable-bindings は (タブ区切りではなく) コンマ区切りのリストになる
.IP
.\"O The system uptime will be broken down into a human-meaningful format (rather than being a simple integer)
システム稼働時間は (単純な数値ではなく) 人にとって意味のあるフォーマットへ分解される
.\"O .SS Examples:
.SS 例:
.PP
.\"O To get a message like "14:03 TRAP3.1 from humpty.ucd.edu" you 
.\"O could use something like this:
"14:03 TRAP3.1 from humpty.ucd.edu" のようなメッセージを得るには、このようなものを使う:
.PP
.RS
.nf
snmptrapd \-P \-F "%02.2h:%02.2j TRAP%w.%q from %A\en"
.fi
.RE
.PP
.\"O If you want the same thing but in GMT rather than local time, use
ローカル時間ではなくGMT で同様のものが欲しい場合は
.PP
.RS
.nf
snmptrapd \-P \-F "%#02.2h:%#02.2j TRAP%w.%q from %A\en"
.fi
.RE
.\"O .SH LISTENING ADDRESSES
.SH 待受アドレス
.\"O By default,
デフォルトでは
.B snmptrapd
.\"O listens for incoming SNMP TRAP and INFORM packets on UDP port 162 on
.\"O all IPv4 interfaces.  However, it is possible to modify this behaviour
.\"O by specifying one or more listening addresses as arguments to
.\"O .BR snmptrapd .
は、すべての IPv4 インターフェース上の UDP 162 番ポートで SNMP TRAP と INFORM パケットを待ち受ける。
しかしこれは
.BR snmptrapd
へ引数として、 ひとつ あるいは 複数の待受アドレスを指定することで 挙動を変えることが出来る。
.\"O See the
.\"O .I snmpd(8)
.\"O manual page for more information about the format of listening
.\"O addresses.
待受アドレスのフォーマットについての情報は
.I snmpd(8)
マニュアルページを参照。
.\"O .SH NOTIFICATION\-LOG\-MIB SUPPORT
.SH NOTIFICATION\-LOG\-MIB サポート
.\"O As of net-snmp 5.0, the snmptrapd application supports the
.\"O NOTIFICATION\-LOG\-MIB.  It does this by opening an AgentX subagent
net-snmp 5.0 現在、 snmptrapd アプリケーションは NOTIFICATION\-LOG\-MIB をサポートする。
.\"O connection to the master snmpd agent and registering the notification
.\"O log tables.  As long as the snmpd application is started first, it
それはマスター snmpd エージェントへの AgentX サブエージェント接続を開き、
通知ログテーブルを登録することで実現する。
snmpd アプリケーションが先に動き出す限りは
.\"O will attach itself to it and thus you should be able to view the last
.\"O recorded notifications via the nlmLogTable and nlmLogVariableTable.
それ自身をアタッチする。したがって nlmLogTable や nlmLogVariableTable 経由で最後に記録された通知を表示することが出来る。
.\"O See the snmptrapd.conf file and the "doNotRetainNotificationLogs" token
.\"O for turning
.\"O off this support.  See the NOTIFICATION\-LOG\-MIB for more details about
.\"O the MIB itself.
このサポートを無効にするには snmptrapd.conf ファイルと "doNotRetainNotificationLogs" トークンを参照。
MIB 自身についての詳細は NOTIFICATION\-LOG\-MIB を参照。
.\"O .SH EXTENSIBILITY AND CONFIGURATION
.SH 拡張性と設定
.\"O See the
.I snmptrapd.conf(5)
.\"O manual page.
マニュアルページを参照。
.\"O .SH "SEE ALSO"
.SH 関連項目
snmpcmd(1), snmpd(8), printf(3), snmptrapd.conf(5), syslog(8), traptoemail(1), variables(5)
