[components.dbusmenu-qt]
# Upstream Release: 0.37.%{snapshot}%{?dist}
release = { calculation = "static", counter = { source = "release-tag", regex = '^0\.([0-9]+)\.%\{snapshot\}(?:%\{\??dist\})?$' } }
