#!/bin/bash

TAGPREFIX=kubevirt
LABELPREFIX=org.opensuse.kubevirt
REGISTRY=registry.opensuse.org
PKG_VERSION=1.51.0
PKG_RELEASE=1.1

if [ -n "${pkg}" ]; then
    if rpm -q ${pkg}; then
        PKG_VERSION=$(rpm -q --queryformat=%{version} ${pkg})
        PKG_RELEASE=$(rpm -q --queryformat=%{release} ${pkg})
    else
        _pkg=$(find ./repos -name "${pkg}*.rpm")
        PKG_VERSION=$(rpm -qp --queryformat=%{version} ${_pkg})
        PKG_RELEASE=$(rpm -qp --queryformat=%{release} ${_pkg})
    fi
fi
