# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

FROM scratch

COPY targetfs/                  /
COPY aarch64-linux-gnu/lib/     /lib
COPY aarch64-linux-gnu/lib64/   /lib64
COPY aarch64-linux-gnu/lib/     /opt/cross/aarch64-linux-gnu/lib
COPY aarch64-linux-gnu/lib64/   /opt/cross/aarch64-linux-gnu/lib64