# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

virtqemud -d
echo "Virtqemud daemon has successfully been created. Starting virt-launcher process."

chmod 0777 /var/run/libvirt
chmod 0777 /var/run/libvirt/*

/usr/bin/virt-launcher
