.TH MSGHACK "1" "June 2013" "msghack" "User Commands"
.SH NAME
msghack \- alter PO files in ways
.SH SYNOPSIS
.B msghack
[\fIOPTION\fR] \fIfile.po \fR[\fIref.po\fR]
.SH DESCRIPTION
.PP
This program can be used to alter .po files in ways no sane mind would think about.
.TP
\fB\-o\fR
result will be written to FILE
.TP
\fB\-\-invert\fR
invert a po file by switching msgid and msgstr
.TP
\fB\-\-master\fR
join any number of files in a master\-formatted catalog
.TP
\fB\-\-empty\fR
empty the contents of the .po file, creating a .pot
.TP
\fB\-\-append\fR
append entries from ref.po that don't exist in file.po
.PP
Note: It is just a replacement of msghack for backward support.
.PP
This program can be used to alter .po files in ways no sane mind would think about.
.TP
\fB\-o\fR
result will be written to FILE
.TP
\fB\-\-invert\fR
invert a po file by switching msgid and msgstr
.TP
\fB\-\-master\fR
join any number of files in a master\-formatted catalog
.TP
\fB\-\-empty\fR
empty the contents of the .po file, creating a .pot
.TP
\fB\-\-append\fR
append entries from ref.po that don't exist in file.po
.PP
Note: It is just a replacement of msghack for backward support.
