## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 6;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

Name:           python-rapidfuzz
Version:        3.12.2
Release:        %autorelease
Summary:        Rapid fuzzy string matching in Python and C++ using the Levenshtein Distance

License:        MIT
URL:            https://github.com/maxbachmann/RapidFuzz
Source:         %{pypi_source rapidfuzz}

BuildRequires:  gcc
BuildRequires:  gcc-c++
BuildRequires:  python3-devel
BuildRequires:  python3-hypothesis
# Pandas will drop i686
# https://bugzilla.redhat.com/show_bug.cgi?id=2263999
BuildRequires:  (python3-pandas or python3(x86-32))
BuildRequires:  python3-pytest
# The PyPi sources don't depend on Cython since they contain pre-generated sources,
# but those are rebuilt for Fedora so Cython must be available.
BuildRequires:  python3-cython >= 3
BuildRequires:  rapidfuzz-cpp-static
BuildRequires:  taskflow-static

%global _description %{expand:
RapidFuzz is a fast string matching library for Python and C++, which is using
the string similarity calculations from FuzzyWuzzy. However there are a couple
of aspects that set RapidFuzz apart from FuzzyWuzzy:
- It is MIT licensed so it can be used whichever License you might want
to choose for your project, while you're forced to adopt the GPL license when
using FuzzyWuzzy
- It provides many string_metrics like hamming or jaro_winkler, which
are not included in FuzzyWuzzy
- It is mostly written in C++ and on top of this comes with a lot of Algorithmic
improvements to make string matching even faster, while still providing the same
results. For detailed benchmarks check the documentation
- Fixes multiple bugs in the partial_ratio implementation}

%description %_description

%package -n python3-rapidfuzz
Summary:        %{summary}

Obsoletes:      python3-rapidfuzz-devel < 3.10
Obsoletes:      python3-rapidfuzz+full < 3.10

%description -n python3-rapidfuzz %_description

%pyproject_extras_subpkg -n python3-rapidfuzz all


%prep
%autosetup -p1 -n rapidfuzz-%{version}
# External dependencies (rapidfuzz-cpp and taskflow) are removed here,
# they are already packaged in Fedora and we BuildRequire them above.
rm extern -r

# Remove pregenerated Cython sources
rm $(grep -rl '/\* Generated by Cython')


%generate_buildrequires
%pyproject_buildrequires -p -x all


%build
# Prevent build without C extensions
export RAPIDFUZZ_BUILD_EXTENSION=1

# To avoid empty debugsourcefiles.list, we need to build the package
# with RelWithDebInfo
# Upstream issue: https://github.com/scikit-build/scikit-build-core/issues/915
export SKBUILD_CMAKE_BUILD_TYPE=RelWithDebInfo
%pyproject_wheel


%install
%pyproject_install
%pyproject_save_files rapidfuzz


%check
# Check section disabled: Disabling checks for initial set of failures.
exit 0

%pytest -v


%files -n python3-rapidfuzz -f %{pyproject_files}
%doc README.*


%changelog
## START: Generated by rpmautospec
* Thu Apr 30 2026 Daniel McIlvaney <damcilva@microsoft.com> - 3.12.2-6
- test: add initial lock files

* Fri Sep 19 2025 Python Maint <python-maint@redhat.com> - 3.12.2-5
- Rebuilt for Python 3.14.0rc3 bytecode

* Fri Aug 15 2025 Python Maint <python-maint@redhat.com> - 3.12.2-4
- Rebuilt for Python 3.14.0rc2 bytecode

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 3.12.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Wed Jun 04 2025 Python Maint <python-maint@redhat.com> - 3.12.2-2
- Rebuilt for Python 3.14

* Thu Mar 27 2025 Tomáš Hrnčiar <thrnciar@redhat.com> - 3.12.2-1
- Update to 3.12.2

* Fri Feb 28 2025 Cristian Le <git@lecris.dev> - 3.11.0-3
- Fix pyproject.toml metadata

* Sat Jan 18 2025 Fedora Release Engineering <releng@fedoraproject.org> - 3.11.0-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Tue Dec 31 2024 Troy Curtis Jr <troy@troycurtisjr.com> - 3.11.0-1
- Update to 3.11.0
- Fixes rhbz#2321558

* Mon Sep 30 2024 Tomáš Hrnčiar <thrnciar@redhat.com> - 3.10.0-1
- Update to 3.10.0
- Fixes: rhbz#2255898

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 3.5.2-8
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Sat Jun 08 2024 Python Maint <python-maint@redhat.com> - 3.5.2-7
- Rebuilt for Python 3.13

* Thu Mar 07 2024 Miro Hrončok <miro@hroncok.cz> - 3.5.2-6
- Make the pandas BuildRequirement rich rather than %%ifnarch conditional

* Wed Mar 06 2024 Sandro <devel@penguinpee.nl> - 3.5.2-5
- Drop dependency on pandas for i686

* Fri Jan 26 2024 Fedora Release Engineering <releng@fedoraproject.org> - 3.5.2-4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Mon Jan 22 2024 Fedora Release Engineering <releng@fedoraproject.org> - 3.5.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_40_Mass_Rebuild

* Thu Jan 18 2024 Tomáš Hrnčiar <thrnciar@redhat.com> - 3.5.2-2
- Add missing sources

* Fri Dec 15 2023 Tomáš Hrnčiar <thrnciar@redhat.com> - 3.5.2-1
- Update to 3.5.2
- Fixes: rhbz#2183537

* Mon Aug 07 2023 Troy Curtis Jr <troy@troycurtisjr.com> - 2.13.7-8
- Fix build for Cython 3.0.0.

* Mon Aug 07 2023 Miro Hrončok <miro@hroncok.cz> - 2.13.7-7
- Build with Cython 3

* Fri Jul 21 2023 Fedora Release Engineering <releng@fedoraproject.org> - 2.13.7-6
- Rebuilt for https://fedoraproject.org/wiki/Fedora_39_Mass_Rebuild

* Sat Jul 01 2023 Python Maint <python-maint@redhat.com> - 2.13.7-5
- Rebuilt for Python 3.12

* Thu Jun 01 2023 Tomáš Hrnčiar <thrnciar@redhat.com> - 2.13.7-4
- Remove pregenerated Cython 3 sources and recreate them with Cython 0.29.x

* Fri Feb 10 2023 Tomáš Hrnčiar <thrnciar@redhat.com> - 2.13.7-1
- Initial package

## END: Generated by rpmautospec
