#!/bin/bash -e

# If using normal root, avoid changing anything.
if [ -z "$RPM_BUILD_ROOT" -o "$RPM_BUILD_ROOT" = "/" ]; then
  exit 0
fi

# Defined as %py_reproducible_pyc_path macro and passed here as
# the first command-line argument
path_to_fix=$1

# First, check that the parser is available:
if [ ! -x /usr/bin/marshalparser ]; then
  echo "ERROR: If %py_reproducible_pyc_path is defined, you have to also BuildRequire: /usr/bin/marshalparser !"
  exit 1
fi

# Set pipefail so if $path_to_fix does not exist, the build fails
set -o pipefail
find "$path_to_fix" -type f -name "*.pyc" | xargs /usr/bin/marshalparser --fix --overwrite
