.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ACPIEXAMPLES 1 "August 8, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
acpiexamples \- program showing what the code examples actually do
.SH SYNOPSIS
.B acpiexamples

.SH DESCRIPTION
This manual page briefly documents the
.B acpiexamples
command. This command has no options available.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.B acpiexamples
prints out the results of various calls using the ACPICA source code,
showing what happens when the calls are made.  These results are from
building and running the code provided in the
/usr/share/doc/acpica-tools/examples directory that illustrate the
proper sequencing of calls and how to make them.
.PP
Much more detailed documentation about ACPICA may be found at
http://www.acpica.org/documentation/.

.SH OPTIONS

.PP
None

.SH AUTHOR
acpiexamples was written by Robert Moore <robert.moore@intel.com>.
.PP
This manual page was written by Al Stone <ahs3@redhat.com> for the
Fedora project (but may be used by others).
