.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ACPIXTRACT 1 "January 23, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
acpixtract \- ACPICA source code conversion utility
.SH SYNOPSIS
.B acpixtract
.RI [ <option> ... ]
.RI <acpidump-file>

.SH DESCRIPTION
This manual page briefly documents the
.B acpixtract
command. The option list is taken from the acpixtract interactive help.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.B acpixtract
extracts binary ACPI tables from the output of the
.B acpidump
command (see the
.B pm-tools
package).  A default invocation will extract the DSDT and
all SSDTs.
.PP
Much more detailed documentation may be found at
http://www.acpica.org/documentation/.

.SH OPTIONS

.PP
.TP
.B \-a
Extract all tables, not just DSDT/SSDT
.TP
.B \-l
List table summaries, do not extract
.TP
.B \-s <signature>
Extract all tables with <signature>

.SH AUTHOR
acpixtract was written by Robert Moore <robert.moore@intel.com>.
.PP
This manual page was written by Al Stone <ahs3@redhat.com> for the
Fedora project (but may be used by others).
