#!/bin/bash

set -e; set -o pipefail

. /etc/sysconfig/heimdal

if [[ -z "$MASTER" ]]; then
   echo >&2 "MASTER must be specified in /etc/sysconfig/heimdal"
   exit 1
fi

exec /usr/libexec/ipropd-slave --detach "$MASTER"
