#!/usr/bin/bash

set -e

if test "$UID" != "0"; then
	echo "p11-kit: the 'extract-trust' command must be run as root" >&2
	exit 2
fi

if test $# -gt 1; then
	echo "p11-kit: no additional arguments are supported for this command" >&2
	exit 2
fi

exec /usr/bin/update-ca-trust
