## START: Set by rpmautospec
## (rpmautospec version 0.8.3)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 3;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

# This spec file has been modified by azldev to include build configuration overlays.
# Do not edit manually; changes may be overwritten.

Name:           python-lxml-html-clean
Version:        0.4.3
Release:        %autorelease
Summary:        HTML cleaner from lxml project
License:        BSD-3-Clause
URL:            https://github.com/fedora-python/lxml_html_clean/
Source:         %{url}/archive/refs/tags/%{version}.tar.gz

BuildArch:      noarch
BuildRequires:  python3-devel

%global _description %{expand:
HTML cleaner from lxml project.}

%description %_description

%package -n     python3-lxml-html-clean
Summary:        %{summary}

%description -n python3-lxml-html-clean %_description


%prep
%autosetup -p1 -n lxml_html_clean-%{version}
sed -i "/memory_profiler/d" tox.ini
# This test requires newer version of libxml2
# https://src.fedoraproject.org/rpms/libxml2/pull-request/16
rm tests/test_clean.txt
sed -i "s@tests/test_clean.txt@@" tox.ini


%generate_buildrequires
%pyproject_buildrequires -t


%build
%pyproject_wheel


%install
%pyproject_install
%pyproject_save_files -l lxml_html_clean


%check
%tox


%files -n python3-lxml-html-clean -f %{pyproject_files}
%doc CHANGES.rst README.md


%changelog
## START: Generated by rpmautospec
* Thu Apr 30 2026 Daniel McIlvaney <damcilva@microsoft.com> - 0.4.3-3
- test: add initial lock files

* Sat Jan 17 2026 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.3-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Thu Oct 02 2025 Lumir Balhar <lbalhar@redhat.com> - 0.4.3-1
- Update to 0.4.3 (rhbz#2401162)

* Fri Sep 19 2025 Python Maint <python-maint@redhat.com> - 0.4.2-5
- Rebuilt for Python 3.14.0rc3 bytecode

* Fri Aug 15 2025 Python Maint <python-maint@redhat.com> - 0.4.2-4
- Rebuilt for Python 3.14.0rc2 bytecode

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.2-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Tue Jun 03 2025 Python Maint <python-maint@redhat.com> - 0.4.2-2
- Rebuilt for Python 3.14

* Wed Apr 09 2025 Lumir Balhar <lbalhar@redhat.com> - 0.4.2-1
- Update to 0.4.2 (rhbz#2358616)

* Sat Jan 18 2025 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Fri Nov 15 2024 Lumir Balhar <lbalhar@redhat.com> - 0.4.1-1
- Update to 0.4.1 (rhbz#2326402)

* Thu Nov 14 2024 Lumir Balhar <lbalhar@redhat.com> - 0.4.0-1
- Update to 0.4.0 (rhbz#2326207)

* Wed Oct 09 2024 Lumir Balhar <lbalhar@redhat.com> - 0.3.1-1
- Update to 0.3.1 (rhbz#2317556)

* Sat Aug 31 2024 Lumir Balhar <lbalhar@redhat.com> - 0.2.2-1
- Update to 0.2.2 (rhbz#2308678)

* Tue Jul 30 2024 Lumir Balhar <lbalhar@redhat.com> - 0.2.0-1
- Update to 0.2.0 (rhbz#2300445)

* Fri Jul 19 2024 Fedora Release Engineering <releng@fedoraproject.org> - 0.1.1-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_41_Mass_Rebuild

* Fri Jun 07 2024 Python Maint <python-maint@redhat.com> - 0.1.1-2
- Rebuilt for Python 3.13

* Fri Apr 05 2024 Lumir Balhar <lbalhar@redhat.com> - 0.1.1-1
- Update to 0.1.1 (rhbz#2273563)

* Tue Apr 02 2024 Lumir Balhar <lbalhar@redhat.com> - 0.1.0-1
- Initial import (fedora#2272620).
## END: Generated by rpmautospec
