#!/bin/sh
if [ $# -ne 0 ]; then
  /usr/sbin/modprobe -abr "$@"
else
  echo "No sensors with loadable kernel modules configured."
  echo "Please, run 'sensors-detect' as root in order to search for available sensors."
  exit 1
fi
