apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: allow-hostnetwork
spec:
  seLinux:
    rule: RunAsAny
  privileged: true
  allowedCapabilities:
    - NET_ADMIN
  volumes:
    - hostPath
    - secret
  hostNetwork: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowedHostPaths:
    - pathPrefix: /etc/kubernetes/azure.json
    - pathPrefix: /run/xtables.lock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:allow-hostnetwork
  namespace: default
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - allow-hostnetwork
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default:allow-hostnetwork
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:allow-hostnetwork
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io