.TH XERCES-J2-CONSTANTS 1 "08 April 2013" "xerces-2.11.0" "User commands"

.SH NAME
xerces-j2-constants \- display constants used by Xerces2 Java Parser

.SH SYNOPSIS
.BR xerces-j2-constants

.SH DESCRIPTION

Xerces-J2-Constants dumps common constants used by Xerces2 Java Parser
to standard output.
