.TH TYPER\-UTILS "1" "April 2024" "" "User Commands"
.SH NAME
.B typer\-utils
\(en extra utility commands for Typer apps
.SH SYNOPSIS
.B typer
.RI [ PATH_OR_MODULE ]
.B utils
.RI [ OPTIONS ]
.I COMMAND
.RI [ ARGS ]...
.SH OPTIONS
.SS ARGUMENTS
.SS OPTIONS
.TP
.B \-\-help
Show a help message and exit.
.SS COMMANDS
.TP
.B docs
Generate Markdown docs for a Typer app.
.IP
See
.BR typer\-utils\-docs (1).
.SH "SEE ALSO"
.BR typer\-utils\-docs (1)
.P
.BR typer (1)
