# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# This action checks that the licenses.json file is up-to-date
# and that the LICENSES-MAP.md file is up-to-date
name: Spec License Map Check

on:
  push:
    branches: [main, dev, 1.0*, 2.0*, 3.0*, fasttrack/*]
  pull_request:
    branches: [main, dev, 1.0*, 2.0*, 3.0*, fasttrack/*]

permissions:
  contents: read

jobs:
  check:
    name: Spec License Map Check
    runs-on: ubuntu-latest

    steps:
      # Checkout the branch of our repo that triggered this action
      - name: Workflow trigger checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Python 3.12
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.12

      - name: Get Python dependencies
        run: python3 -m pip install python-rpm-spec

      - name: Run license map checking script
        run: |
          python3 ./toolkit/scripts/license_map.py \
          ./LICENSES-AND-NOTICES/SPECS/data/licenses.json \
          ./LICENSES-AND-NOTICES/SPECS/LICENSES-MAP.md \
          ./SPECS \
          ./SPECS-EXTENDED \
          ./SPECS-SIGNED
