# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# Workflow to automatedly verify the quickstart instructions

name: Verify Quickstart 3.0

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"

jobs:
  iso_quickstart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: '3.0-stable'

    - name: Set up Go 1.21
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
      id: go

    - name: Install Remaining Prerequisites
      run: |
        # Golang and docker are already installed on the agent
        sudo apt-get update
        sudo apt -y install \
            acl \
            curl \
            gawk \
            genisoimage \
            git \
            golang-1.21-go \
            jq \
            make \
            parted \
            pigz \
            openssl \
            systemd \
            qemu-utils \
            rpm \
            tar \
            wget \
            xfsprogs

        # Fix go 1.21 link
        sudo ln -vsf /usr/lib/go-1.21/bin/go /usr/bin/go
        sudo ln -vsf /usr/lib/go-1.21/bin/gofmt /usr/bin/gofmt

    - name: ISO Quick Start
      run: |
        pushd toolkit
        sudo make iso REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/full.json
        popd

  vhdx_quickstart:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: '3.0-stable'

    - name: Set up Go 1.21
      uses: actions/setup-go@v5
      with:
        go-version: 1.21
      id: go

    - name: Install Remaining Prerequisites
      run: |
        # Golang and docker are already installed on the agent
        sudo apt -y install \
            acl \
            curl \
            gawk \
            genisoimage \
            git \
            golang-1.21-go \
            jq \
            make \
            parted \
            pigz \
            openssl \
            systemd \
            qemu-utils \
            rpm \
            tar \
            wget \
            xfsprogs

        # Fix go 1.21 link
        sudo ln -vsf /usr/lib/go-1.21/bin/go /usr/bin/go
        sudo ln -vsf /usr/lib/go-1.21/bin/gofmt /usr/bin/gofmt
    - name: VHDX Quick Start
      run: |
        pushd toolkit
        sudo make image REBUILD_TOOLS=y REBUILD_PACKAGES=n CONFIG_FILE=./imageconfigs/core-efi.json
        popd